CREATE TRIGGER attempt_cancellation_intents_protect_server_terminal BEFORE UPDATE ON attempt_cancellation_intents FOR EACH ROW EXECUTE FUNCTION automata_protect_server_cancellation_intent();

CREATE TRIGGER attempt_log_streams_output_safety_immutable BEFORE UPDATE ON attempt_log_streams FOR EACH ROW EXECUTE FUNCTION automata_attempt_log_safety_immutable();

CREATE TRIGGER attempt_log_streams_validate_output_safety BEFORE INSERT ON attempt_log_streams FOR EACH ROW EXECUTE FUNCTION automata_validate_attempt_log_safety_snapshot();

CREATE TRIGGER attempt_terminal_results_assign_logical_workflow_order AFTER INSERT ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_assign_logical_workflow_terminal_ordinal();

CREATE TRIGGER attempt_terminal_results_protect_result_evidence BEFORE UPDATE ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_protect_attempt_terminal_result_evidence();

CREATE TRIGGER attempt_terminal_results_protect_logical_workflow_order BEFORE UPDATE ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_protect_logical_workflow_terminal_ordinal();

CREATE TRIGGER attempt_terminal_results_refresh_result_projection_due AFTER INSERT OR UPDATE ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_terminal_result_due_trigger();

CREATE TRIGGER attempt_terminal_results_reject_retained_delete BEFORE DELETE ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_reject_retained_attempt_terminal_result_delete();

CREATE TRIGGER attempt_terminal_results_reject_truncate BEFORE TRUNCATE ON attempt_terminal_results FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER attempt_terminal_results_validate_server_cancellation BEFORE INSERT OR UPDATE ON attempt_terminal_results FOR EACH ROW EXECUTE FUNCTION automata_validate_server_cancellation_terminal();

CREATE TRIGGER concurrency_group_pending_runs_validate_distinct BEFORE INSERT OR UPDATE ON concurrency_group_pending_runs FOR EACH ROW EXECUTE FUNCTION automata_validate_concurrency_pending_run();

CREATE TRIGGER concurrency_groups_validate_running_distinct BEFORE INSERT OR UPDATE ON concurrency_groups FOR EACH ROW EXECUTE FUNCTION automata_validate_concurrency_running_run();

CREATE TRIGGER github_check_projection_outbox_00_credential_rejection_guard BEFORE UPDATE ON github_check_projection_outbox FOR EACH ROW EXECUTE FUNCTION automata_github_check_credential_rejection_guard();

CREATE TRIGGER github_check_projection_outbox_no_delete BEFORE DELETE ON github_check_projection_outbox FOR EACH ROW EXECUTE FUNCTION automata_reject_github_check_removal();

CREATE TRIGGER github_check_projection_outbox_no_truncate BEFORE TRUNCATE ON github_check_projection_outbox FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_check_removal();

CREATE TRIGGER github_check_projection_outbox_update_guard BEFORE UPDATE ON github_check_projection_outbox FOR EACH ROW EXECUTE FUNCTION automata_github_check_outbox_update_guard();

CREATE TRIGGER github_check_subjects_00_canonical_name BEFORE INSERT ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_canonical_name();

CREATE TRIGGER github_check_subjects_00_delivery_evidence_exact BEFORE INSERT ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_delivery_evidence_exact();

CREATE TRIGGER github_check_subjects_00_origin_immutable BEFORE UPDATE ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_origin_immutable();

CREATE TRIGGER github_check_subjects_canonical_name_immutable BEFORE UPDATE ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_canonical_name_immutable();

CREATE TRIGGER github_check_subjects_create_projection_outbox AFTER INSERT ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_create_github_check_projection_outbox();

CREATE TRIGGER github_check_subjects_insert_guard BEFORE INSERT ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_insert_guard();

CREATE TRIGGER github_check_subjects_no_delete BEFORE DELETE ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_reject_github_check_removal();

CREATE TRIGGER github_check_subjects_no_truncate BEFORE TRUNCATE ON github_check_subjects FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_check_removal();

CREATE CONSTRAINT TRIGGER github_check_subjects_require_atomic_rerun_evidence AFTER INSERT ON github_check_subjects DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_workflow_rerun_check_requires_atomic_evidence();

CREATE CONSTRAINT TRIGGER github_check_subjects_require_atomic_schedule_evidence AFTER INSERT ON github_check_subjects DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_github_schedule_check_requires_atomic_evidence();

CREATE CONSTRAINT TRIGGER github_check_subjects_require_rerun_link_evidence AFTER UPDATE OF workflow_run_id, linked_at_ms, desired_state, desired_revision, desired_updated_at_ms ON github_check_subjects DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_workflow_rerun_link_requires_run_evidence();

CREATE TRIGGER github_check_subjects_update_guard BEFORE UPDATE ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_github_check_subject_update_guard();

CREATE TRIGGER github_check_subjects_wake_projection AFTER UPDATE ON github_check_subjects FOR EACH ROW EXECUTE FUNCTION automata_wake_github_check_projection();

CREATE TRIGGER github_oidc_authorities_00_historical_standard_profile BEFORE INSERT ON github_oidc_authorities FOR EACH ROW EXECUTE FUNCTION automata_require_standard_github_oidc_profile();

CREATE TRIGGER github_oidc_authorities_insert_guard BEFORE INSERT ON github_oidc_authorities FOR EACH ROW EXECUTE FUNCTION automata_validate_github_oidc_authority_insert();

CREATE TRIGGER github_oidc_authorities_reject_update BEFORE DELETE OR UPDATE ON github_oidc_authorities FOR EACH ROW EXECUTE FUNCTION automata_reject_github_oidc_authority_mutation();

CREATE TRIGGER github_oidc_issuance_slots_reject_delete BEFORE DELETE ON github_oidc_issuance_slots FOR EACH ROW EXECUTE FUNCTION automata_reject_github_oidc_issuance_delete();

CREATE TRIGGER github_oidc_issuance_slots_replace BEFORE UPDATE ON github_oidc_issuance_slots FOR EACH ROW EXECUTE FUNCTION automata_enforce_github_oidc_issuance_replacement();

CREATE TRIGGER github_oidc_issuance_slots_validate BEFORE INSERT OR UPDATE ON github_oidc_issuance_slots FOR EACH ROW EXECUTE FUNCTION automata_validate_github_oidc_issuance_slot();

CREATE TRIGGER github_oidc_key_deadlines_monotonic BEFORE UPDATE ON github_oidc_key_deadlines FOR EACH ROW EXECUTE FUNCTION automata_enforce_github_oidc_key_deadline();

CREATE TRIGGER github_oidc_key_deadlines_reject_delete BEFORE DELETE ON github_oidc_key_deadlines FOR EACH ROW EXECUTE FUNCTION automata_reject_github_oidc_issuance_delete();

CREATE TRIGGER github_provider_delivery_evidence_00_authenticated_event BEFORE INSERT ON github_provider_delivery_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_authenticated_event_exact();

CREATE TRIGGER github_provider_delivery_evidence_00_insert_guard BEFORE INSERT ON github_provider_delivery_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_provider_delivery_evidence_insert_guard();

CREATE TRIGGER github_provider_delivery_evidence_no_truncate BEFORE TRUNCATE ON github_provider_delivery_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_github_provider_delivery_evidence_immutable();

CREATE TRIGGER github_provider_delivery_evidence_no_update_delete BEFORE DELETE OR UPDATE ON github_provider_delivery_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_provider_delivery_evidence_immutable();

CREATE TRIGGER github_provider_manifest_current_guard BEFORE INSERT OR DELETE OR UPDATE ON github_provider_manifest_current FOR EACH ROW EXECUTE FUNCTION automata_github_provider_manifest_current_guard();

CREATE TRIGGER github_provider_manifest_current_no_truncate BEFORE TRUNCATE ON github_provider_manifest_current FOR EACH STATEMENT EXECUTE FUNCTION automata_github_provider_manifest_current_no_truncate();

CREATE CONSTRAINT TRIGGER github_provider_manifest_current_requires_runtime_policy AFTER INSERT OR UPDATE ON github_provider_manifest_current DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_current_manifest_runtime_policy_pair();

CREATE CONSTRAINT TRIGGER github_provider_manifest_revision_must_be_current AFTER INSERT ON github_provider_manifest_revisions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_inserted_manifest_revision_current();

CREATE TRIGGER github_provider_manifest_revisions_00_canonical_guard BEFORE INSERT ON github_provider_manifest_revisions FOR EACH ROW EXECUTE FUNCTION automata_github_provider_manifest_canonical_guard();

CREATE TRIGGER github_provider_manifest_revisions_01_runtime_policy BEFORE INSERT ON github_provider_manifest_revisions FOR EACH ROW EXECUTE FUNCTION automata_require_github_manifest_runtime_policy();

CREATE TRIGGER github_provider_manifest_revisions_no_truncate BEFORE TRUNCATE ON github_provider_manifest_revisions FOR EACH STATEMENT EXECUTE FUNCTION automata_github_provider_manifest_revision_immutable();

CREATE TRIGGER github_provider_manifest_revisions_no_update BEFORE DELETE OR UPDATE ON github_provider_manifest_revisions FOR EACH ROW EXECUTE FUNCTION automata_github_provider_manifest_revision_immutable();

CREATE TRIGGER github_provider_manifest_revisions_repository_exact BEFORE INSERT ON github_provider_manifest_revisions FOR EACH ROW EXECUTE FUNCTION automata_github_provider_manifest_repository_exact();

CREATE TRIGGER github_repository_dispatch_pending_00_insert_guard BEFORE INSERT ON github_repository_dispatch_pending_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_repository_dispatch_pending_insert_guard();

CREATE TRIGGER github_repository_dispatch_pending_no_truncate BEFORE TRUNCATE ON github_repository_dispatch_pending_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_github_repository_dispatch_pending_immutable();

CREATE TRIGGER github_repository_dispatch_pending_no_update_delete BEFORE DELETE OR UPDATE ON github_repository_dispatch_pending_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_repository_dispatch_pending_immutable();

CREATE TRIGGER github_role_mappings_authorization_revision AFTER INSERT OR DELETE OR UPDATE ON github_role_mappings FOR EACH ROW EXECUTE FUNCTION automata_github_mapping_authorization_revision();

CREATE TRIGGER github_runtime_authority_00_graph_guard_update BEFORE UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_validate_github_runtime_authority_identity();

CREATE TRIGGER github_runtime_authority_00_identity_guard BEFORE INSERT ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_validate_github_runtime_authority_identity();

CREATE TRIGGER github_runtime_authority_00z_clear_stale_operation_request BEFORE UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_clear_stale_github_runtime_authority_operation_request();

CREATE TRIGGER github_runtime_authority_01_database_time_guard BEFORE INSERT OR UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_database_time();

CREATE TRIGGER github_runtime_authority_02_lifecycle_guard BEFORE UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_enforce_github_runtime_authority_lifecycle();

CREATE TRIGGER github_runtime_authority_03_capture_claim_evidence AFTER INSERT OR UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_capture_github_runtime_authority_claim_evidence();

CREATE TRIGGER github_runtime_authority_03b_capture_mint_begin AFTER UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_capture_github_runtime_authority_mint_begin();

CREATE TRIGGER github_runtime_authority_04_capture_operation_transition AFTER UPDATE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_capture_github_runtime_authority_operation_transition();

CREATE TRIGGER github_runtime_authority_insert_guard BEFORE INSERT ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_validate_github_runtime_authority_insert();

CREATE CONSTRAINT TRIGGER github_runtime_authority_lease_renewal_final_exact AFTER INSERT ON github_runtime_authority_lease_renewal_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_github_runtime_authority_lease_final_exact();

CREATE TRIGGER github_runtime_authority_lease_renewal_receipts_reject_mutation BEFORE DELETE OR UPDATE ON github_runtime_authority_lease_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_reject_github_runtime_authority_lease_renewal_mutation();

CREATE TRIGGER github_runtime_authority_lease_renewal_receipts_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_lease_renewal_receipts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_lease_renewal_mutation();

CREATE TRIGGER github_runtime_authority_lease_renewal_receipts_validate BEFORE INSERT ON github_runtime_authority_lease_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_validate_github_runtime_authority_lease_renewal();

CREATE TRIGGER github_runtime_authority_mint_begins_guard BEFORE INSERT OR DELETE OR UPDATE ON github_runtime_authority_mint_begins FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_mint_begin();

CREATE TRIGGER github_runtime_authority_mint_begins_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_mint_begins FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_claim_evidence_truncat();

CREATE TRIGGER github_runtime_authority_mint_claims_guard BEFORE INSERT OR DELETE OR UPDATE ON github_runtime_authority_mint_claims FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_mint_claim();

CREATE TRIGGER github_runtime_authority_mint_claims_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_mint_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_claim_evidence_truncat();

CREATE TRIGGER github_runtime_authority_no_delete BEFORE DELETE ON github_runtime_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_reject_github_runtime_authority_removal();

CREATE TRIGGER github_runtime_authority_no_truncate BEFORE TRUNCATE ON github_runtime_authority_issuances FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_removal();

CREATE TRIGGER github_runtime_authority_operation_receipts_00_validate BEFORE INSERT ON github_runtime_authority_operation_receipts FOR EACH ROW EXECUTE FUNCTION automata_validate_github_runtime_authority_operation_receipt();

CREATE TRIGGER github_runtime_authority_operation_receipts_guard BEFORE DELETE OR UPDATE ON github_runtime_authority_operation_receipts FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_operation_receipt();

CREATE TRIGGER github_runtime_authority_operation_receipts_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_operation_receipts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_operation_receipt_trun();

CREATE CONSTRAINT TRIGGER github_runtime_authority_operation_transition_receipt AFTER INSERT ON github_runtime_authority_operation_transitions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_github_runtime_authority_operation_receipt();

CREATE TRIGGER github_runtime_authority_operation_transitions_guard BEFORE INSERT OR DELETE OR UPDATE ON github_runtime_authority_operation_transitions FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_operation_transition();

CREATE TRIGGER github_runtime_authority_operation_transitions_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_operation_transitions FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_operation_receipt_trun();

CREATE TRIGGER github_runtime_authority_revocation_claims_guard BEFORE INSERT OR DELETE OR UPDATE ON github_runtime_authority_revocation_claims FOR EACH ROW EXECUTE FUNCTION automata_guard_github_runtime_authority_revocation_claim();

CREATE TRIGGER github_runtime_authority_revocation_claims_reject_truncate BEFORE TRUNCATE ON github_runtime_authority_revocation_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_runtime_authority_claim_evidence_truncat();

CREATE TRIGGER github_schedule_check_evidence_00_insert_guard BEFORE INSERT ON github_schedule_check_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_schedule_check_evidence_insert_guard();

CREATE TRIGGER github_schedule_check_evidence_immutable BEFORE DELETE OR UPDATE ON github_schedule_check_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_check_evidence_reject_truncate BEFORE TRUNCATE ON github_schedule_check_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_discovery_claims_00_insert_guard BEFORE INSERT ON github_schedule_discovery_claims FOR EACH ROW EXECUTE FUNCTION automata_guard_github_schedule_discovery_claim_insert();

CREATE TRIGGER github_schedule_discovery_claims_reject_truncate BEFORE TRUNCATE ON github_schedule_discovery_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_discovery_claims_transition_exact BEFORE DELETE OR UPDATE ON github_schedule_discovery_claims FOR EACH ROW EXECUTE FUNCTION automata_guard_github_schedule_discovery_claim_transition();

CREATE TRIGGER github_schedule_fire_attempts_immutable BEFORE DELETE OR UPDATE ON github_schedule_fire_attempts FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_fire_attempts_reject_truncate BEFORE TRUNCATE ON github_schedule_fire_attempts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_fires_reject_truncate BEFORE TRUNCATE ON github_schedule_fires FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE CONSTRAINT TRIGGER github_schedule_fires_terminal_evidence AFTER INSERT OR UPDATE ON github_schedule_fires DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_github_schedule_fire_terminal_evidence();

CREATE TRIGGER github_schedule_fires_transition_exact BEFORE DELETE OR UPDATE ON github_schedule_fires FOR EACH ROW EXECUTE FUNCTION automata_guard_github_schedule_fire_transition();

CREATE TRIGGER github_schedule_registry_entries_00_require_unsealed BEFORE INSERT ON github_schedule_registry_entries FOR EACH ROW EXECUTE FUNCTION automata_guard_github_schedule_registry_entry_insert();

CREATE TRIGGER github_schedule_registry_entries_immutable BEFORE DELETE OR UPDATE ON github_schedule_registry_entries FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_registry_entries_reject_truncate BEFORE TRUNCATE ON github_schedule_registry_entries FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_registry_revisions_00_insert_guard BEFORE INSERT ON github_schedule_registry_revisions FOR EACH ROW EXECUTE FUNCTION automata_guard_github_schedule_registry_revision_insert();

CREATE TRIGGER github_schedule_registry_revisions_immutable BEFORE DELETE OR UPDATE ON github_schedule_registry_revisions FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_registry_revisions_reject_truncate BEFORE TRUNCATE ON github_schedule_registry_revisions FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_registry_seals_exact BEFORE INSERT ON github_schedule_registry_seals FOR EACH ROW EXECUTE FUNCTION automata_seal_github_schedule_registry();

CREATE TRIGGER github_schedule_registry_seals_immutable BEFORE DELETE OR UPDATE ON github_schedule_registry_seals FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_registry_seals_reject_truncate BEFORE TRUNCATE ON github_schedule_registry_seals FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_schedule_workflow_run_subject_evidence_00_insert_guard BEFORE INSERT ON github_schedule_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_schedule_run_evidence_insert_guard();

CREATE TRIGGER github_schedule_workflow_run_subject_evidence_10_pin_runtime_po AFTER INSERT ON github_schedule_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_pin_github_scheduled_workflow_runtime_policy();

CREATE TRIGGER github_schedule_workflow_run_subject_evidence_immutable BEFORE DELETE OR UPDATE ON github_schedule_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_github_schedule_immutable_mutation();

CREATE TRIGGER github_schedule_workflow_run_subject_evidence_reject_truncate BEFORE TRUNCATE ON github_schedule_workflow_run_subject_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_github_schedule_evidence_truncate();

CREATE TRIGGER github_server_service_authorities_insert_guard BEFORE INSERT ON github_server_service_authorities FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_authority_insert_guard();

CREATE CONSTRAINT TRIGGER github_server_service_authorities_issuance_pointer_exact AFTER INSERT OR UPDATE ON github_server_service_authorities DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_issuance_pointer_exact();

CREATE TRIGGER github_server_service_authorities_no_delete BEFORE DELETE ON github_server_service_authorities FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_authorities_no_truncate BEFORE TRUNCATE ON github_server_service_authorities FOR EACH STATEMENT EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_authorities_update_guard BEFORE UPDATE ON github_server_service_authorities FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_authority_update_guard();

CREATE TRIGGER github_server_service_handoffs_insert_guard BEFORE INSERT ON github_server_service_authority_handoffs FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_handoff_insert_guard();

CREATE TRIGGER github_server_service_handoffs_no_delete BEFORE DELETE ON github_server_service_authority_handoffs FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_handoffs_no_truncate BEFORE TRUNCATE ON github_server_service_authority_handoffs FOR EACH STATEMENT EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_handoffs_update_guard BEFORE UPDATE ON github_server_service_authority_handoffs FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_handoff_update_guard();

CREATE CONSTRAINT TRIGGER github_server_service_issuances_authority_pointer_exact AFTER INSERT OR UPDATE ON github_server_service_authority_issuances DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_issuance_pointer_exact();

CREATE TRIGGER github_server_service_issuances_insert_guard BEFORE INSERT ON github_server_service_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_issuance_insert_guard();

CREATE TRIGGER github_server_service_issuances_no_delete BEFORE DELETE ON github_server_service_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_issuances_no_truncate BEFORE TRUNCATE ON github_server_service_authority_issuances FOR EACH STATEMENT EXECUTE FUNCTION automata_github_server_service_reject_removal();

CREATE TRIGGER github_server_service_issuances_update_guard BEFORE UPDATE ON github_server_service_authority_issuances FOR EACH ROW EXECUTE FUNCTION automata_github_server_service_issuance_update_guard();

CREATE TRIGGER github_workflow_rerun_subject_evidence_00_insert_guard BEFORE INSERT ON github_workflow_rerun_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_validate_github_workflow_rerun_subject_evidence();

CREATE TRIGGER github_workflow_rerun_subject_evidence_no_truncate BEFORE TRUNCATE ON github_workflow_rerun_subject_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_subject_evidence_mutation();

CREATE TRIGGER github_workflow_rerun_subject_evidence_no_update_delete BEFORE DELETE OR UPDATE ON github_workflow_rerun_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_subject_evidence_mutation();

CREATE TRIGGER github_workflow_run_subject_evidence_00_insert_guard BEFORE INSERT ON github_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_workflow_run_subject_evidence_insert_guard();

CREATE TRIGGER github_workflow_run_subject_evidence_10_pin_runtime_policy AFTER INSERT ON github_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_pin_github_workflow_runtime_policy();

CREATE TRIGGER github_workflow_run_subject_evidence_no_truncate BEFORE TRUNCATE ON github_workflow_run_subject_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_github_workflow_run_subject_evidence_immutable();

CREATE TRIGGER github_workflow_run_subject_evidence_no_update_delete BEFORE DELETE OR UPDATE ON github_workflow_run_subject_evidence FOR EACH ROW EXECUTE FUNCTION automata_github_workflow_run_subject_evidence_immutable();

CREATE TRIGGER installation_state_lifecycle_guard BEFORE UPDATE ON installation_state FOR EACH ROW EXECUTE FUNCTION automata_enforce_installation_state_lifecycle();

CREATE TRIGGER installation_state_no_insert_delete BEFORE INSERT OR DELETE ON installation_state FOR EACH ROW EXECUTE FUNCTION automata_reject_installation_singleton_replacement();

CREATE TRIGGER installation_state_no_truncate BEFORE TRUNCATE ON installation_state FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_installation_singleton_replacement();

CREATE TRIGGER human_login_transactions_lifecycle_guard BEFORE UPDATE ON human_login_transactions FOR EACH ROW EXECUTE FUNCTION automata_enforce_human_login_transaction_lifecycle();

CREATE TRIGGER human_provider_tokens_lifecycle_guard BEFORE DELETE OR UPDATE ON human_provider_tokens FOR EACH ROW EXECUTE FUNCTION automata_enforce_provider_token_lifecycle();

CREATE TRIGGER human_sessions_activation_lifecycle_guard BEFORE INSERT OR UPDATE OF session_kind, audience, lifecycle_status, activation_deadline_ms, activated_at_ms, issued_at_ms, expires_at_ms, revision ON human_sessions FOR EACH ROW EXECUTE FUNCTION guard_human_session_activation_lifecycle();

CREATE TRIGGER job_attempts_00_require_runner_requirements_current BEFORE INSERT ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_require_runner_requirements_current_attempt();

CREATE TRIGGER job_attempts_00_require_variable_custody_before_lease BEFORE UPDATE ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_reject_job_variable_lease_without_custody();

CREATE TRIGGER job_attempts_01_require_current_environment_gate_before_lease BEFORE UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_require_current_job_environment_gate_before_lease();

CREATE TRIGGER job_attempts_cancel_pending_environment_gate AFTER UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_cancel_pending_environment_gate_for_attempt();

CREATE TRIGGER job_attempts_expire_managed_secret_delivery AFTER UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_expire_managed_secret_delivery_for_attempt();

CREATE CONSTRAINT TRIGGER job_attempts_github_runtime_authority_renewal_exact AFTER UPDATE ON job_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW WHEN (((new.lease_expires_at_ms IS NOT NULL) AND (old.lease_expires_at_ms IS DISTINCT FROM new.lease_expires_at_ms) AND (new.lifecycle = ANY (ARRAY['leased'::text, 'preparing'::text, 'running'::text, 'cancelling'::text])))) EXECUTE FUNCTION automata_require_github_runtime_authority_attempt_renewal();

CREATE TRIGGER job_attempts_output_safety_immutable BEFORE UPDATE ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_job_attempt_output_safety_immutable();

CREATE TRIGGER job_attempts_project_github_check AFTER UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_project_job_attempt_to_github_check();

CREATE TRIGGER job_attempts_refresh_result_projection_due_after_terminal AFTER UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_attempt_lifecycle_due_trigger();

CREATE TRIGGER job_attempts_require_environment_gate_before_lease BEFORE UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_require_job_environment_gate_before_lease();

CREATE TRIGGER job_attempts_require_secret_bindings_before_preparing BEFORE UPDATE OF lifecycle ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_require_secret_bindings_before_preparing();

CREATE TRIGGER job_attempts_seed_environment_gate AFTER INSERT ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_seed_retry_job_environment_gate();

CREATE TRIGGER job_attempts_started_at_guard BEFORE INSERT OR UPDATE ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_job_attempt_started_at_guard();

CREATE TRIGGER job_attempts_terminal_monotonic BEFORE UPDATE ON job_attempts FOR EACH ROW EXECUTE FUNCTION automata_job_attempt_terminal_monotonic();

CREATE TRIGGER job_environment_gates_guard BEFORE UPDATE ON job_environment_gates FOR EACH ROW EXECUTE FUNCTION automata_job_environment_gate_guard();

CREATE TRIGGER job_missing_secret_bindings_append_only BEFORE DELETE OR UPDATE ON job_missing_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_job_binding_append_only();

CREATE TRIGGER job_missing_secret_bindings_exact BEFORE INSERT ON job_missing_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_missing_job_secret();

CREATE TRIGGER job_missing_secret_bindings_validate BEFORE INSERT ON job_missing_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_job_credential_binding();

CREATE TRIGGER job_missing_variable_bindings_append_only BEFORE DELETE OR UPDATE ON job_missing_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_job_binding_append_only();

CREATE TRIGGER job_missing_variable_bindings_exact BEFORE INSERT ON job_missing_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_missing_job_variable();

CREATE TRIGGER job_missing_variable_bindings_validate BEFORE INSERT ON job_missing_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_job_credential_binding();

CREATE TRIGGER job_secret_bindings_append_only BEFORE DELETE OR UPDATE ON job_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_job_binding_append_only();

CREATE TRIGGER job_secret_bindings_exact BEFORE INSERT ON job_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_job_secret_binding_exact();

CREATE TRIGGER job_secret_selections_append_only BEFORE DELETE OR UPDATE ON job_secret_selections FOR EACH ROW EXECUTE FUNCTION automata_job_binding_append_only();

CREATE TRIGGER job_secret_selections_exact BEFORE INSERT ON job_secret_selections FOR EACH ROW EXECUTE FUNCTION automata_validate_job_secret_selection_exact();

CREATE TRIGGER job_secret_selections_validate BEFORE INSERT ON job_secret_selections FOR EACH ROW EXECUTE FUNCTION automata_validate_job_credential_binding();

CREATE TRIGGER job_variable_bindings_append_only BEFORE DELETE OR UPDATE ON job_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_job_binding_append_only();

CREATE TRIGGER job_variable_bindings_exact BEFORE INSERT ON job_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_job_variable_binding_exact();

CREATE TRIGGER job_variable_bindings_validate BEFORE INSERT ON job_variable_bindings FOR EACH ROW EXECUTE FUNCTION automata_validate_job_credential_binding();

CREATE TRIGGER jobs_00_require_runner_requirements_current BEFORE INSERT ON jobs FOR EACH ROW EXECUTE FUNCTION automata_require_runner_requirements_current();

CREATE TRIGGER jobs_plan_immutable BEFORE UPDATE ON jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_job_plan_update();

CREATE TRIGGER managed_secret_delivery_operations_guard BEFORE UPDATE ON managed_secret_delivery_operations FOR EACH ROW EXECUTE FUNCTION automata_managed_secret_delivery_operation_guard();

CREATE TRIGGER managed_secret_delivery_operations_no_delete BEFORE DELETE OR TRUNCATE ON managed_secret_delivery_operations FOR EACH STATEMENT EXECUTE FUNCTION automata_managed_secret_delivery_no_delete();

CREATE TRIGGER protected_environment_approval_decisions_immutable BEFORE DELETE OR UPDATE ON protected_environment_approval_decisions FOR EACH ROW EXECUTE FUNCTION automata_protected_environment_decision_immutable();

CREATE TRIGGER protected_environment_approval_decisions_no_truncate BEFORE TRUNCATE ON protected_environment_approval_decisions FOR EACH STATEMENT EXECUTE FUNCTION automata_protected_environment_decision_immutable();

CREATE TRIGGER protected_environment_approval_decisions_reviewer BEFORE INSERT ON protected_environment_approval_decisions FOR EACH ROW EXECUTE FUNCTION automata_require_environment_reviewer();

CREATE TRIGGER protected_environment_approval_decisions_validate BEFORE INSERT ON protected_environment_approval_decisions FOR EACH ROW EXECUTE FUNCTION automata_validate_environment_approval_decision();

CREATE TRIGGER protected_environment_approval_snapshot BEFORE INSERT OR UPDATE ON protected_environment_approval_requests FOR EACH ROW EXECUTE FUNCTION automata_protected_environment_approval_snapshot();

CREATE TRIGGER protected_environment_approval_threshold_proven_guard BEFORE UPDATE ON protected_environment_approval_requests FOR EACH ROW EXECUTE FUNCTION automata_prove_protected_environment_approval_resolution();

CREATE TRIGGER provider_delivery_inbox_lifecycle_guard BEFORE UPDATE ON provider_delivery_inbox FOR EACH ROW EXECUTE FUNCTION automata_enforce_provider_delivery_lifecycle();

CREATE TRIGGER provider_delivery_inbox_no_delete BEFORE DELETE ON provider_delivery_inbox FOR EACH ROW EXECUTE FUNCTION automata_reject_provider_delivery_removal();

CREATE TRIGGER provider_delivery_inbox_no_truncate BEFORE TRUNCATE ON provider_delivery_inbox FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_provider_delivery_removal();

CREATE CONSTRAINT TRIGGER provider_delivery_inbox_require_atomic_github_check AFTER INSERT ON provider_delivery_inbox DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_github_delivery_requires_atomic_queued_check();

CREATE CONSTRAINT TRIGGER provider_delivery_inbox_workflow_progress_completion AFTER UPDATE OF state ON provider_delivery_inbox DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_provider_delivery_workflow_progress_completion();

CREATE TRIGGER provider_delivery_workflow_inventories_00_insert_guard BEFORE INSERT ON provider_delivery_workflow_inventories FOR EACH ROW EXECUTE FUNCTION automata_guard_provider_delivery_workflow_inventory();

CREATE CONSTRAINT TRIGGER provider_delivery_workflow_inventories_digest_canonical AFTER INSERT ON provider_delivery_workflow_inventories DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_verify_provider_delivery_workflow_inventory();

CREATE TRIGGER provider_delivery_workflow_inventories_no_mutation BEFORE DELETE OR UPDATE ON provider_delivery_workflow_inventories FOR EACH ROW EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER provider_delivery_workflow_inventories_no_truncate BEFORE TRUNCATE ON provider_delivery_workflow_inventories FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER provider_delivery_workflow_inventory_entries_00_insert_guard BEFORE INSERT ON provider_delivery_workflow_inventory_entries FOR EACH ROW EXECUTE FUNCTION automata_guard_provider_delivery_workflow_inventory_entry();

CREATE CONSTRAINT TRIGGER provider_delivery_workflow_inventory_entries_digest_canonical AFTER INSERT ON provider_delivery_workflow_inventory_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_verify_provider_delivery_workflow_inventory();

CREATE TRIGGER provider_delivery_workflow_inventory_entries_no_mutation BEFORE DELETE OR UPDATE ON provider_delivery_workflow_inventory_entries FOR EACH ROW EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER provider_delivery_workflow_inventory_entries_no_truncate BEFORE TRUNCATE ON provider_delivery_workflow_inventory_entries FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER provider_delivery_workflow_outcomes_insert_guard BEFORE INSERT ON provider_delivery_workflow_outcomes FOR EACH ROW EXECUTE FUNCTION automata_enforce_provider_delivery_outcome_insert();

CREATE TRIGGER provider_delivery_workflow_outcomes_no_truncate BEFORE TRUNCATE ON provider_delivery_workflow_outcomes FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_provider_delivery_outcome_mutation();

CREATE TRIGGER provider_delivery_workflow_outcomes_no_update_delete BEFORE DELETE OR UPDATE ON provider_delivery_workflow_outcomes FOR EACH ROW EXECUTE FUNCTION automata_reject_provider_delivery_outcome_mutation();

CREATE TRIGGER provider_delivery_workflow_progress_00_insert_guard BEFORE INSERT ON provider_delivery_workflow_progress FOR EACH ROW EXECUTE FUNCTION automata_guard_provider_delivery_workflow_progress();

CREATE TRIGGER provider_delivery_workflow_progress_no_mutation BEFORE DELETE OR UPDATE ON provider_delivery_workflow_progress FOR EACH ROW EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER provider_delivery_workflow_progress_no_truncate BEFORE TRUNCATE ON provider_delivery_workflow_progress FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_provider_delivery_workflow_progress_mutation();

CREATE TRIGGER rbac_role_bindings_authorization_revision AFTER INSERT OR DELETE OR UPDATE ON rbac_role_bindings FOR EACH ROW EXECUTE FUNCTION automata_role_binding_authorization_revision();

CREATE TRIGGER rbac_role_permissions_authorization_revision AFTER INSERT OR DELETE OR UPDATE ON rbac_role_permissions FOR EACH ROW EXECUTE FUNCTION automata_role_permission_authorization_revision();

CREATE TRIGGER repositories_github_provider_manifest_identity_immutable BEFORE UPDATE ON repositories FOR EACH ROW EXECUTE FUNCTION automata_github_provider_manifest_repository_identity_immutable();

CREATE TRIGGER repositories_seed_publication_policy AFTER INSERT ON repositories FOR EACH ROW EXECUTE FUNCTION automata_seed_repository_publication_policy();

CREATE TRIGGER repository_environment_reviewers_guard BEFORE INSERT OR DELETE OR UPDATE ON repository_environment_reviewers FOR EACH ROW EXECUTE FUNCTION automata_repository_environment_reviewer_guard();

CREATE TRIGGER repository_environment_reviewers_no_truncate BEFORE TRUNCATE ON repository_environment_reviewers FOR EACH STATEMENT EXECUTE FUNCTION automata_repository_environment_reviewer_guard();

CREATE TRIGGER repository_environments_revision_guard BEFORE UPDATE ON repository_environments FOR EACH ROW EXECUTE FUNCTION automata_repository_environment_revision_guard();

CREATE CONSTRAINT TRIGGER runner_cancellation_payload_retention AFTER INSERT OR UPDATE ON attempt_cancellation_intents DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_assert_cancellation_payload_retention();

CREATE TRIGGER runner_command_outbox_payload_guard AFTER INSERT OR UPDATE ON runner_command_outbox FOR EACH ROW EXECUTE FUNCTION automata_guard_runner_command_payload();

CREATE CONSTRAINT TRIGGER runner_command_outbox_payload_retention AFTER INSERT OR UPDATE ON runner_command_outbox DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_assert_runner_payload_row_retention();

CREATE TRIGGER runner_command_outbox_tombstone_retain BEFORE DELETE ON runner_command_outbox FOR EACH ROW EXECUTE FUNCTION automata_retain_runner_payload_tombstone();

CREATE TRIGGER runner_lease_offer_authority_horizon_guard BEFORE UPDATE OF offer_valid_until_ms ON runner_lease_offer_publications FOR EACH ROW EXECUTE FUNCTION automata_enforce_runner_lease_offer_authority_horizon();

CREATE TRIGGER runner_lease_offer_delivery_revocation_guard BEFORE INSERT OR UPDATE ON runner_lease_offer_publications FOR EACH ROW EXECUTE FUNCTION automata_enforce_runner_lease_offer_delivery_revocation();

CREATE TRIGGER runner_machine_certificates_authority_immutable BEFORE UPDATE OF leaf_sha256, runner_id, expires_at_seconds ON runner_machine_certificates FOR EACH ROW EXECUTE FUNCTION automata_runner_certificate_authority_immutable();

CREATE TRIGGER runner_machine_certificates_revocation_write_once BEFORE UPDATE OF revoked_at_seconds ON runner_machine_certificates FOR EACH ROW EXECUTE FUNCTION automata_runner_certificate_revocation_write_once();

CREATE TRIGGER runner_enrollment_tokens_consume_once BEFORE UPDATE ON runner_enrollment_tokens FOR EACH ROW EXECUTE FUNCTION automata_runner_enrollment_token_consume_once();

CREATE TRIGGER runner_rpc_receipt_lease_offer_binding_guard BEFORE UPDATE OF lease_offer_request_operation_id, lease_offer_command_sequence, lease_offer_response_disposition, lease_offer_primary_response_schema, lease_offer_primary_response_digest, lease_offer_fallback_version, lease_offer_fallback_operation_id, lease_offer_fallback_retry_after_millis, lease_offer_fallback_response_schema, lease_offer_fallback_response_digest ON runner_rpc_receipts FOR EACH ROW EXECUTE FUNCTION automata_enforce_runner_rpc_receipt_lease_offer_binding();

CREATE TRIGGER runner_rpc_receipts_payload_guard AFTER INSERT OR UPDATE ON runner_rpc_receipts FOR EACH ROW EXECUTE FUNCTION automata_guard_runner_rpc_payload();

CREATE CONSTRAINT TRIGGER runner_rpc_receipts_payload_retention AFTER INSERT OR UPDATE ON runner_rpc_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_assert_runner_payload_row_retention();

CREATE TRIGGER runner_rpc_receipts_tombstone_retain BEFORE DELETE ON runner_rpc_receipts FOR EACH ROW EXECUTE FUNCTION automata_retain_runner_payload_tombstone();

CREATE CONSTRAINT TRIGGER runner_session_payload_retention AFTER INSERT OR UPDATE ON runner_sessions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_assert_runner_session_payload_retention();

CREATE TRIGGER runner_sessions_expire_managed_secret_delivery AFTER UPDATE OF disconnected_at_ms ON runner_sessions FOR EACH ROW EXECUTE FUNCTION automata_expire_managed_secret_delivery_for_session();

CREATE TRIGGER secret_cleanup_delete_guard BEFORE DELETE ON secret_cleanup_outbox FOR EACH ROW EXECUTE FUNCTION automata_secret_cleanup_delete_guard();

CREATE TRIGGER secret_cleanup_transition_guard BEFORE INSERT OR UPDATE ON secret_cleanup_outbox FOR EACH ROW EXECUTE FUNCTION automata_secret_cleanup_transition_guard();

CREATE TRIGGER secret_cleanup_truncate_guard BEFORE TRUNCATE ON secret_cleanup_outbox FOR EACH STATEMENT EXECUTE FUNCTION automata_secret_cleanup_delete_guard();

CREATE TRIGGER secret_custody_key_canaries_delete_forbidden BEFORE DELETE ON secret_custody_key_canaries FOR EACH ROW EXECUTE FUNCTION automata_secret_custody_key_canaries_immutable();

CREATE TRIGGER secret_custody_key_canaries_fresh_key BEFORE INSERT ON secret_custody_key_canaries FOR EACH ROW EXECUTE FUNCTION automata_secret_custody_canary_require_fresh_key();

CREATE TRIGGER secret_custody_key_canaries_truncate_forbidden BEFORE TRUNCATE ON secret_custody_key_canaries FOR EACH STATEMENT EXECUTE FUNCTION automata_secret_custody_key_canaries_immutable();

CREATE TRIGGER secret_custody_key_canaries_update_forbidden BEFORE UPDATE ON secret_custody_key_canaries FOR EACH ROW EXECUTE FUNCTION automata_secret_custody_key_canaries_immutable();

CREATE TRIGGER secret_key_rotation_items_validate_envelopes BEFORE INSERT OR UPDATE ON secret_key_rotation_items FOR EACH ROW EXECUTE FUNCTION automata_validate_secret_key_rotation_item();

CREATE TRIGGER secret_mutation_recovery_complete_on_terminal AFTER UPDATE ON secret_version_mutations FOR EACH ROW EXECUTE FUNCTION automata_complete_secret_mutation_recovery();

CREATE TRIGGER secret_mutation_recovery_delete_guard BEFORE DELETE ON secret_mutation_recovery_outbox FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_recovery_delete_guard();

CREATE TRIGGER secret_mutation_recovery_insert_guard BEFORE INSERT ON secret_version_mutations FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_recovery_insert_guard();

CREATE CONSTRAINT TRIGGER secret_mutation_recovery_mutation_guard AFTER INSERT OR UPDATE ON secret_version_mutations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_recovery_deferred_guard();

CREATE CONSTRAINT TRIGGER secret_mutation_recovery_outbox_guard AFTER INSERT OR UPDATE ON secret_mutation_recovery_outbox DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_recovery_deferred_guard();

CREATE TRIGGER secret_mutation_recovery_transition_guard BEFORE INSERT OR UPDATE ON secret_mutation_recovery_outbox FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_recovery_transition_guard();

CREATE TRIGGER secret_mutation_recovery_truncate_guard BEFORE TRUNCATE ON secret_mutation_recovery_outbox FOR EACH STATEMENT EXECUTE FUNCTION automata_secret_mutation_recovery_delete_guard();

CREATE TRIGGER secret_provider_configuration_envelopes_delete_guard BEFORE DELETE ON secret_provider_configuration_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_configuration_delete_guard();

CREATE TRIGGER secret_provider_configuration_envelopes_immutable BEFORE UPDATE ON secret_provider_configuration_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_configuration_envelopes_immutable();

CREATE TRIGGER secret_provider_lease_envelopes_delete_guard BEFORE DELETE ON secret_provider_lease_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_lease_delete_guard();

CREATE TRIGGER secret_provider_lease_envelopes_immutable BEFORE UPDATE ON secret_provider_lease_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_reference_envelopes_immutable();

CREATE TRIGGER secret_provider_locator_envelopes_delete_guard BEFORE DELETE ON secret_provider_locator_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_locator_delete_guard();

CREATE TRIGGER secret_provider_locator_envelopes_immutable BEFORE UPDATE ON secret_provider_locator_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_reference_envelopes_immutable();

CREATE TRIGGER secret_provider_version_envelopes_delete_guard BEFORE DELETE ON secret_provider_version_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_version_envelope_delete_guard();

CREATE TRIGGER secret_provider_version_envelopes_immutable BEFORE UPDATE ON secret_provider_version_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_provider_reference_envelopes_immutable();

CREATE TRIGGER secret_version_envelopes_delete_guard BEFORE DELETE ON secret_version_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_version_envelope_delete_guard();

CREATE TRIGGER secret_version_envelopes_immutable BEFORE UPDATE ON secret_version_envelopes FOR EACH ROW EXECUTE FUNCTION automata_secret_version_envelopes_immutable();

CREATE CONSTRAINT TRIGGER secret_version_lifecycle_deferred_guard AFTER INSERT OR UPDATE ON secret_version_lifecycle DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_secret_version_lifecycle_deferred_guard();

CREATE TRIGGER secret_version_lifecycle_delete_guard BEFORE DELETE ON secret_version_lifecycle FOR EACH ROW EXECUTE FUNCTION automata_secret_version_lifecycle_delete_guard();

CREATE TRIGGER secret_version_lifecycle_insert_guard BEFORE INSERT ON secret_version_lifecycle FOR EACH ROW EXECUTE FUNCTION automata_secret_version_lifecycle_insert_guard();

CREATE TRIGGER secret_version_lifecycle_transition BEFORE UPDATE ON secret_version_lifecycle FOR EACH ROW EXECUTE FUNCTION automata_secret_version_lifecycle_transition();

CREATE TRIGGER secret_version_lifecycle_truncate_guard BEFORE TRUNCATE ON secret_version_lifecycle FOR EACH STATEMENT EXECUTE FUNCTION automata_secret_version_lifecycle_delete_guard();

CREATE TRIGGER secret_version_mutations_delete_guard BEFORE DELETE ON secret_version_mutations FOR EACH ROW EXECUTE FUNCTION automata_secret_version_mutation_delete_guard();

CREATE TRIGGER secret_version_mutations_insert_guard BEFORE INSERT ON secret_version_mutations FOR EACH ROW EXECUTE FUNCTION automata_secret_version_mutation_insert_guard();

CREATE CONSTRAINT TRIGGER secret_version_mutations_terminal_deferred_guard AFTER UPDATE ON secret_version_mutations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_secret_mutation_terminal_deferred_guard();

CREATE TRIGGER secret_version_mutations_transition BEFORE UPDATE ON secret_version_mutations FOR EACH ROW EXECUTE FUNCTION automata_secret_version_mutation_transition();

CREATE TRIGGER secret_version_mutations_truncate_guard BEFORE TRUNCATE ON secret_version_mutations FOR EACH STATEMENT EXECUTE FUNCTION automata_secret_version_mutation_delete_guard();

CREATE CONSTRAINT TRIGGER secret_versions_deferred_mutation_stage AFTER INSERT ON secret_versions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_secret_version_deferred_guard();

CREATE TRIGGER secret_versions_immutable BEFORE DELETE OR UPDATE ON secret_versions FOR EACH ROW EXECUTE FUNCTION automata_secret_versions_immutable();

CREATE TRIGGER secret_workload_grants_current_reviewer_authority BEFORE INSERT ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_require_current_approval_before_secret_grant();

CREATE TRIGGER secret_workload_grants_environment_current BEFORE INSERT ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_secret_workload_grant_environment_current();

CREATE TRIGGER secret_workload_grants_identity_immutable BEFORE UPDATE ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_secret_workload_grant_identity_immutable();

CREATE TRIGGER secret_workload_grants_invocation_guard BEFORE UPDATE ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_secret_workload_grant_invocation_guard();

CREATE TRIGGER secret_workload_grants_terminal_monotonic BEFORE UPDATE ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_secret_workload_grant_terminal_monotonic();

CREATE TRIGGER secret_workload_grants_validate BEFORE INSERT ON secret_workload_grants FOR EACH ROW EXECUTE FUNCTION automata_validate_secret_workload_grant();

CREATE TRIGGER secrets_cancel_version_mutations_on_update_delete AFTER UPDATE ON secrets FOR EACH ROW EXECUTE FUNCTION automata_cancel_secret_version_mutations_on_delete();

CREATE TRIGGER secrets_descriptor_immutable BEFORE UPDATE ON secrets FOR EACH ROW EXECUTE FUNCTION automata_secret_descriptor_immutable();

CREATE TRIGGER secrets_seed_policy AFTER INSERT ON secrets FOR EACH ROW EXECUTE FUNCTION automata_seed_secret_policy();

CREATE TRIGGER security_audit_events_append_only_rows BEFORE DELETE OR UPDATE ON security_audit_events FOR EACH ROW EXECUTE FUNCTION automata_security_audit_events_append_only();

CREATE TRIGGER security_audit_events_append_only_truncate BEFORE TRUNCATE ON security_audit_events FOR EACH STATEMENT EXECUTE FUNCTION automata_security_audit_events_append_only();

CREATE TRIGGER tenant_human_memberships_authorization_revision BEFORE UPDATE ON tenant_human_memberships FOR EACH ROW EXECUTE FUNCTION automata_membership_status_authorization_revision();

CREATE TRIGGER tenants_seed_builtin_secret_provider AFTER INSERT ON tenants FOR EACH ROW EXECUTE FUNCTION automata_seed_builtin_secret_provider();

CREATE TRIGGER workflow_admission_github_evidence_flag_immutable BEFORE UPDATE ON workflow_admission_receipts FOR EACH ROW EXECUTE FUNCTION automata_workflow_admission_github_evidence_flag_immutable();

CREATE CONSTRAINT TRIGGER workflow_admission_require_github_evidence AFTER INSERT OR UPDATE ON workflow_admission_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_required_github_subject_evidence_committed();

CREATE TRIGGER workflow_artifacts_output_safety_immutable BEFORE UPDATE ON workflow_artifacts FOR EACH ROW EXECUTE FUNCTION automata_artifact_safety_immutable();

CREATE TRIGGER workflow_artifacts_validate_output_safety BEFORE INSERT ON workflow_artifacts FOR EACH ROW EXECUTE FUNCTION automata_validate_artifact_safety_snapshot();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_claim_lineage AFTER UPDATE ON logical_workflow_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_activation_claim_lineage();
