CREATE TRIGGER logical_workflow_activation_preparation_base_context_exact BEFORE INSERT ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_preparation_base_context();

CREATE TRIGGER logical_workflow_activation_preparation_base_context_immutable BEFORE UPDATE OF base_context_digest, base_context_object_key, base_context_size_bytes, base_context_media_type, base_context_schema ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_preparation_base_context_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_preparation_claim_complete AFTER INSERT OR UPDATE ON logical_workflow_activation_preparation_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_complete();

CREATE TRIGGER logical_workflow_activation_preparation_claims_00_profile BEFORE INSERT ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_activation_preparation_authority_profile();

CREATE TRIGGER logical_workflow_activation_preparation_claims_enforce_update BEFORE UPDATE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_activation_preparation_claim_update();

CREATE TRIGGER logical_workflow_activation_preparation_claims_profile_immutabl BEFORE UPDATE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_preparation_authority_profile();

CREATE TRIGGER logical_workflow_activation_preparation_claims_reject_delete BEFORE DELETE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_activation_preparation_claim_delete();

CREATE TRIGGER logical_workflow_activation_preparation_claims_validate BEFORE INSERT ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_claim();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_preparation_output_complete AFTER INSERT ON logical_workflow_activation_preparation_outputs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_complete();

CREATE TRIGGER logical_workflow_activation_preparation_outputs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_activation_preparation_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_activation_preparation_mutation();

CREATE TRIGGER logical_workflow_activation_preparation_outputs_validate BEFORE INSERT ON logical_workflow_activation_preparation_outputs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_output();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_preparation_pin_complete AFTER INSERT ON logical_workflow_activation_preparation_prerequisites DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_complete();

CREATE TRIGGER logical_workflow_activation_preparation_prerequisites_reject_mu BEFORE DELETE OR UPDATE ON logical_workflow_activation_preparation_prerequisites FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_activation_preparation_mutation();

CREATE TRIGGER logical_workflow_activation_preparation_prerequisites_validate BEFORE INSERT ON logical_workflow_activation_preparation_prerequisites FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_prerequisite();

CREATE TRIGGER logical_workflow_activation_preparations_00_profile BEFORE INSERT ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_validate_prepared_authority_profile();

CREATE TRIGGER logical_workflow_activation_preparations_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_activation_preparation_mutation();

CREATE TRIGGER logical_workflow_activation_preparations_validate BEFORE INSERT ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_activation_preparation_binding();

CREATE TRIGGER logical_workflow_activation_publications_00_profile BEFORE INSERT ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_validate_activation_publication_authority_profile();

CREATE TRIGGER logical_workflow_activation_publications_refresh_result_due AFTER INSERT ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_activation_due_trigger();

CREATE TRIGGER logical_workflow_activation_publications_reject_delete BEFORE DELETE ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_publication_delete();

CREATE TRIGGER logical_workflow_activation_publications_reject_truncate BEFORE TRUNCATE ON logical_workflow_activation_publications FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_activation_publications_reject_update BEFORE UPDATE ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_publication_update();

CREATE TRIGGER logical_workflow_activation_publications_validate BEFORE INSERT ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_activation_publication();

CREATE TRIGGER logical_workflow_activation_quarantine_immutable BEFORE DELETE OR UPDATE ON logical_workflow_activation_work_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_quarantine_selection_closure AFTER INSERT ON logical_workflow_activation_work_quarantines DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_final_activation_work_quarantine();

CREATE TRIGGER logical_workflow_activation_quarantine_truncate BEFORE TRUNCATE ON logical_workflow_activation_work_quarantines FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_activation_quarantine_validate BEFORE INSERT ON logical_workflow_activation_work_quarantines FOR EACH ROW EXECUTE FUNCTION automata_validate_activation_real_claim_quarantine();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_renewal_receipt_delete_guard AFTER DELETE ON logical_workflow_activation_renewal_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_renewal_receipt_parent_deleted();

CREATE TRIGGER logical_workflow_activation_renewal_receipt_reject_truncate BEFORE TRUNCATE ON logical_workflow_activation_renewal_receipts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_activation_renewal_receipt_reject_update BEFORE UPDATE ON logical_workflow_activation_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_activation_renewal_receipt_validate BEFORE INSERT ON logical_workflow_activation_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_validate_activation_real_claim_renewal_receipt();

CREATE TRIGGER logical_workflow_activation_selection_delete BEFORE DELETE ON logical_workflow_activation_work_selections FOR EACH ROW EXECUTE FUNCTION automata_enforce_activation_selection_receipt_delete();

CREATE CONSTRAINT TRIGGER logical_workflow_activation_selection_finalize AFTER INSERT OR UPDATE ON logical_workflow_activation_work_selections DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_final_activation_work_selection();

CREATE TRIGGER logical_workflow_activation_selection_truncate BEFORE TRUNCATE ON logical_workflow_activation_work_selections FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_activation_selection_validate BEFORE INSERT OR UPDATE ON logical_workflow_activation_work_selections FOR EACH ROW EXECUTE FUNCTION automata_validate_activation_work_selection_transition();

CREATE CONSTRAINT TRIGGER logical_workflow_concrete_job_closure AFTER INSERT ON logical_workflow_concrete_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_materialization_state_closure();

CREATE TRIGGER logical_workflow_concrete_jobs_00_profile BEFORE INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_concrete_job_authority_profile();

CREATE TRIGGER logical_workflow_concrete_jobs_00_require_runner_requirements_v BEFORE INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_require_runner_requirements_current();

CREATE TRIGGER logical_workflow_concrete_jobs_00_runtime_policy BEFORE INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_concrete_jobs_01_live_authority BEFORE INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_require_live_concrete_job_authority();

CREATE TRIGGER logical_workflow_concrete_jobs_policy_immutable BEFORE UPDATE ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_concrete_jobs_reject_delete BEFORE DELETE ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_concrete_jobs_reject_truncate BEFORE TRUNCATE ON logical_workflow_concrete_jobs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_concrete_jobs_reject_update BEFORE UPDATE ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_concrete_job_update();

CREATE TRIGGER logical_workflow_concrete_jobs_seed_environment_gate AFTER INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_seed_initial_job_environment_gate();

CREATE TRIGGER logical_workflow_concrete_jobs_validate BEFORE INSERT ON logical_workflow_concrete_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_concrete_job();

CREATE TRIGGER logical_workflow_concurrency_cancellations_reject_delete BEFORE DELETE ON logical_workflow_concurrency_cancellations FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_concurrency_cancellation_mutat();

CREATE TRIGGER logical_workflow_concurrency_cancellations_reject_truncate BEFORE TRUNCATE ON logical_workflow_concurrency_cancellations FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_concurrency_cancellation_mutat();

CREATE TRIGGER logical_workflow_concurrency_cancellations_reject_update BEFORE UPDATE ON logical_workflow_concurrency_cancellations FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_concurrency_cancellation_mutat();

CREATE TRIGGER logical_workflow_concurrency_cancellations_validate BEFORE INSERT ON logical_workflow_concurrency_cancellations FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_concurrency_cancellation();

CREATE TRIGGER logical_workflow_dependencies_01_admission_graph_open BEFORE INSERT ON logical_workflow_dependencies FOR EACH ROW EXECUTE FUNCTION automata_require_open_workflow_admission_graph();

CREATE TRIGGER logical_workflow_dependencies_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_dependencies FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_dependencies_reject_delete BEFORE DELETE ON logical_workflow_dependencies FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_dependencies_reject_truncate BEFORE TRUNCATE ON logical_workflow_dependencies FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_dependencies_reject_update BEFORE UPDATE ON logical_workflow_dependencies FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_dependency_update();

CREATE CONSTRAINT TRIGGER logical_workflow_dependencies_validate_rerun_graph AFTER INSERT ON logical_workflow_dependencies DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_graph_exact();

CREATE CONSTRAINT TRIGGER logical_workflow_instance_count_exact AFTER INSERT OR DELETE OR UPDATE ON logical_workflow_instances DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_count();

CREATE TRIGGER logical_workflow_instance_result_claims_enforce_transition BEFORE UPDATE ON logical_workflow_instance_result_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_instance_result_claim_transit();

CREATE TRIGGER logical_workflow_instance_result_claims_refresh_due AFTER INSERT OR UPDATE ON logical_workflow_instance_result_claims FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_instance_claim_due_trigger();

CREATE TRIGGER logical_workflow_instance_result_claims_reject_delete BEFORE DELETE ON logical_workflow_instance_result_claims FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_claims_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_result_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_claims_validate BEFORE INSERT ON logical_workflow_instance_result_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_result_claim();

CREATE TRIGGER logical_workflow_instance_result_due_enforce_rows BEFORE INSERT OR DELETE OR UPDATE ON logical_workflow_instance_result_due FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_result_due_mutation();

CREATE TRIGGER logical_workflow_instance_result_due_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_result_due FOR EACH STATEMENT EXECUTE FUNCTION automata_enforce_logical_workflow_result_due_mutation();

CREATE TRIGGER logical_workflow_instance_result_outputs_reject_delete BEFORE DELETE ON logical_workflow_instance_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_outputs_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_result_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_outputs_reject_update BEFORE UPDATE ON logical_workflow_instance_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_instance_result_update();

CREATE TRIGGER logical_workflow_instance_result_outputs_validate BEFORE INSERT ON logical_workflow_instance_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_result_output();

CREATE TRIGGER logical_workflow_instance_result_quarantines_reject_delete BEFORE DELETE ON logical_workflow_instance_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_quarantines_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_result_quarantines FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_quarantines_reject_update BEFORE UPDATE ON logical_workflow_instance_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_result_quarantines_validate BEFORE INSERT ON logical_workflow_instance_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_result_quarantine();

CREATE TRIGGER logical_workflow_instance_result_selections_enforce BEFORE UPDATE ON logical_workflow_instance_result_selections FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_instance_result_selection();

CREATE TRIGGER logical_workflow_instance_result_selections_reject_delete BEFORE DELETE ON logical_workflow_instance_result_selections FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_selection_mutation();

CREATE TRIGGER logical_workflow_instance_result_selections_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_result_selections FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_selection_mutation();

CREATE TRIGGER logical_workflow_instance_results_reject_delete BEFORE DELETE ON logical_workflow_instance_results FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_results_reject_truncate BEFORE TRUNCATE ON logical_workflow_instance_results FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instance_results_reject_update BEFORE UPDATE ON logical_workflow_instance_results FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_instance_result_update();

CREATE TRIGGER logical_workflow_instance_results_validate BEFORE INSERT ON logical_workflow_instance_results FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_result();

CREATE TRIGGER logical_workflow_instances_00_runtime_policy BEFORE INSERT ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_instances_01_active_unquarantined BEFORE INSERT ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_require_active_unquarantined_phase_insert();

CREATE TRIGGER logical_workflow_instances_policy_immutable BEFORE UPDATE ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_instances_refresh_result_due AFTER INSERT ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_activation_due_trigger();

CREATE TRIGGER logical_workflow_instances_reject_retained_delete BEFORE DELETE ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_reject_retained_logical_workflow_instance_delete();

CREATE TRIGGER logical_workflow_instances_reject_truncate BEFORE TRUNCATE ON logical_workflow_instances FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_instances_reject_update BEFORE UPDATE ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_instance_update();

CREATE CONSTRAINT TRIGGER logical_workflow_instances_require_environment_evidence AFTER INSERT ON logical_workflow_instances DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_job_environment_activation_evidence();

CREATE TRIGGER logical_workflow_instances_validate BEFORE INSERT ON logical_workflow_instances FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance();

CREATE TRIGGER logical_workflow_invocations_enforce_immutable BEFORE UPDATE ON logical_workflow_invocations FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_invocation_immutable();

CREATE TRIGGER logical_workflow_invocations_guard_run_result BEFORE UPDATE ON logical_workflow_invocations FOR EACH ROW EXECUTE FUNCTION automata_guard_logical_workflow_invocation_run_result();

CREATE TRIGGER logical_workflow_invocations_reject_result_source_delete BEFORE DELETE ON logical_workflow_invocations FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_invocations_reject_result_source_truncate BEFORE TRUNCATE ON logical_workflow_invocations FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_invocations_validate_root BEFORE INSERT OR UPDATE ON logical_workflow_invocations FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_root();

CREATE TRIGGER logical_workflow_job_dependencies_reject BEFORE INSERT OR UPDATE ON job_dependencies FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_dependency();

CREATE TRIGGER logical_workflow_job_environment_evidence_append_only BEFORE DELETE OR UPDATE ON logical_workflow_job_environment_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_job_environment_evidence_mutation();

CREATE TRIGGER logical_workflow_job_environment_evidence_no_truncate BEFORE TRUNCATE ON logical_workflow_job_environment_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_job_environment_evidence_mutation();

CREATE TRIGGER logical_workflow_job_environment_evidence_validate BEFORE INSERT ON logical_workflow_job_environment_evidence FOR EACH ROW EXECUTE FUNCTION automata_validate_job_environment_activation_evidence();

CREATE TRIGGER logical_workflow_job_result_claims_enforce_transition BEFORE UPDATE ON logical_workflow_job_result_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_job_result_claim_transition();

CREATE TRIGGER logical_workflow_job_result_claims_refresh_due AFTER INSERT OR UPDATE ON logical_workflow_job_result_claims FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_job_claim_due_trigger();

CREATE TRIGGER logical_workflow_job_result_claims_reject_delete BEFORE DELETE ON logical_workflow_job_result_claims FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_claims_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_claims_validate BEFORE INSERT ON logical_workflow_job_result_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result_claim();

CREATE TRIGGER logical_workflow_job_result_due_enforce_rows BEFORE INSERT OR DELETE OR UPDATE ON logical_workflow_job_result_due FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_result_due_mutation();

CREATE TRIGGER logical_workflow_job_result_due_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_due FOR EACH STATEMENT EXECUTE FUNCTION automata_enforce_logical_workflow_result_due_mutation();

CREATE TRIGGER logical_workflow_job_result_instances_reject_delete BEFORE DELETE ON logical_workflow_job_result_instances FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_instances_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_instances FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_instances_reject_update BEFORE UPDATE ON logical_workflow_job_result_instances FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_job_result_update();

CREATE TRIGGER logical_workflow_job_result_instances_validate BEFORE INSERT ON logical_workflow_job_result_instances FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result_instance();

CREATE TRIGGER logical_workflow_job_result_outputs_reject_delete BEFORE DELETE ON logical_workflow_job_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_outputs_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_outputs_reject_update BEFORE UPDATE ON logical_workflow_job_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_job_result_update();

CREATE TRIGGER logical_workflow_job_result_outputs_validate BEFORE INSERT ON logical_workflow_job_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result_output();

CREATE TRIGGER logical_workflow_job_result_prerequisites_reject_delete BEFORE DELETE ON logical_workflow_job_result_prerequisites FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_prerequisites_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_prerequisites FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_prerequisites_reject_update BEFORE UPDATE ON logical_workflow_job_result_prerequisites FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_job_result_update();

CREATE TRIGGER logical_workflow_job_result_prerequisites_validate BEFORE INSERT ON logical_workflow_job_result_prerequisites FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result_prerequisite();

CREATE TRIGGER logical_workflow_job_result_quarantines_reject_delete BEFORE DELETE ON logical_workflow_job_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_quarantines_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_quarantines FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_quarantines_reject_update BEFORE UPDATE ON logical_workflow_job_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_result_quarantines_validate BEFORE INSERT ON logical_workflow_job_result_quarantines FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result_quarantine();

CREATE TRIGGER logical_workflow_job_result_selections_enforce BEFORE UPDATE ON logical_workflow_job_result_selections FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_job_result_selection();

CREATE TRIGGER logical_workflow_job_result_selections_reject_delete BEFORE DELETE ON logical_workflow_job_result_selections FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_selection_mutation();

CREATE TRIGGER logical_workflow_job_result_selections_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_result_selections FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_selection_mutation();

CREATE TRIGGER logical_workflow_job_results_reject_delete BEFORE DELETE ON logical_workflow_job_results FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_results_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_results FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_results_reject_update BEFORE UPDATE ON logical_workflow_job_results FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_job_result_update();

CREATE TRIGGER logical_workflow_job_results_validate BEFORE INSERT ON logical_workflow_job_results FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_job_result();

CREATE TRIGGER logical_workflow_job_terminal_counters_enforce BEFORE INSERT OR UPDATE ON logical_workflow_job_terminal_counters FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_terminal_counter();

CREATE TRIGGER logical_workflow_job_terminal_counters_reject_delete BEFORE DELETE ON logical_workflow_job_terminal_counters FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_job_terminal_counters_reject_truncate BEFORE TRUNCATE ON logical_workflow_job_terminal_counters FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_jobs_00_activation_admission BEFORE INSERT ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_require_pristine_logical_job_admission();

CREATE TRIGGER logical_workflow_jobs_01_admission_graph_open BEFORE INSERT ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_require_open_workflow_admission_graph();

CREATE TRIGGER logical_workflow_jobs_02_activation_transition BEFORE UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_activation_claim_transition();

CREATE TRIGGER logical_workflow_jobs_credential_requirements_validate BEFORE INSERT OR UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_job_credential_requirements();

CREATE TRIGGER logical_workflow_jobs_enforce_activation_input BEFORE UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_activation_input();

CREATE TRIGGER logical_workflow_jobs_enforce_authority_profile BEFORE UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_job_authority_profile();

CREATE TRIGGER logical_workflow_jobs_enforce_immutable BEFORE UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_job_immutable();

CREATE TRIGGER logical_workflow_jobs_enforce_runtime_policy BEFORE INSERT OR UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_job_runtime_policy();

CREATE TRIGGER logical_workflow_jobs_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE CONSTRAINT TRIGGER logical_workflow_jobs_preserve_nonempty_root AFTER DELETE ON logical_workflow_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_logical_workflow_nonempty_root();

CREATE TRIGGER logical_workflow_jobs_refresh_result_due AFTER UPDATE OF state ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_refresh_logical_workflow_job_state_due_trigger();

CREATE TRIGGER logical_workflow_jobs_reject_result_source_delete BEFORE DELETE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_jobs_reject_result_source_truncate BEFORE TRUNCATE ON logical_workflow_jobs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_jobs_require_classified_credentials BEFORE UPDATE OF state ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_require_classified_logical_job_credentials();

CREATE CONSTRAINT TRIGGER logical_workflow_jobs_require_instance_link AFTER INSERT ON jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_logical_workflow_concrete_job_link();

CREATE TRIGGER logical_workflow_jobs_rerun_carried_immutable BEFORE UPDATE OF rerun_carried, state, updated_at_ms, activation_fence, activation_owner_id, activation_claimed_at_ms, activation_expires_at_ms, activation_input_digest, authority_profile, activation_origin_selection_id ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_carried_flag_mutation();

CREATE TRIGGER logical_workflow_jobs_validate_activation_transition BEFORE UPDATE ON logical_workflow_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_activation_transition();

CREATE CONSTRAINT TRIGGER logical_workflow_jobs_validate_rerun_classification AFTER INSERT ON logical_workflow_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_job_classification();

CREATE CONSTRAINT TRIGGER logical_workflow_jobs_validate_rerun_graph AFTER INSERT ON logical_workflow_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_graph_exact();

CREATE CONSTRAINT TRIGGER logical_workflow_materialization_claim_closure AFTER INSERT OR UPDATE ON logical_workflow_materialization_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_materialization_state_closure();

CREATE CONSTRAINT TRIGGER logical_workflow_materialization_claim_lineage AFTER INSERT OR UPDATE ON logical_workflow_materialization_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_materialization_claim_lineage();

CREATE TRIGGER logical_workflow_materialization_claims_00_profile BEFORE INSERT ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_materialization_authority_profile();

CREATE TRIGGER logical_workflow_materialization_claims_00_runtime_policy BEFORE INSERT ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_materialization_claims_02_transition BEFORE INSERT OR UPDATE ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_materialization_claim_transition();

CREATE TRIGGER logical_workflow_materialization_claims_enforce_transition BEFORE UPDATE ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_materialization_claim_transit();

CREATE TRIGGER logical_workflow_materialization_claims_policy_immutable BEFORE UPDATE ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_materialization_claims_profile_immutable BEFORE UPDATE ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_materialization_authority_profile();

CREATE TRIGGER logical_workflow_materialization_claims_reject_delete BEFORE DELETE ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_materialization_claims_reject_truncate BEFORE TRUNCATE ON logical_workflow_materialization_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_materialization_claims_validate BEFORE INSERT ON logical_workflow_materialization_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_materialization_claim();

CREATE TRIGGER logical_workflow_materialization_quarantine_immutable BEFORE DELETE OR UPDATE ON logical_workflow_materialization_work_quarantines FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_materialization_quarantine_selection_closure AFTER INSERT ON logical_workflow_materialization_work_quarantines DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_final_materialization_work_quarantine();

CREATE TRIGGER logical_workflow_materialization_quarantine_truncate BEFORE TRUNCATE ON logical_workflow_materialization_work_quarantines FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_materialization_quarantine_validate BEFORE INSERT ON logical_workflow_materialization_work_quarantines FOR EACH ROW EXECUTE FUNCTION automata_validate_materialization_real_claim_quarantine();

CREATE CONSTRAINT TRIGGER logical_workflow_materialization_renewal_receipt_delete_guard AFTER DELETE ON logical_workflow_materialization_renewal_receipts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_renewal_receipt_parent_deleted();

CREATE TRIGGER logical_workflow_materialization_renewal_receipt_reject_truncat BEFORE TRUNCATE ON logical_workflow_materialization_renewal_receipts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_materialization_renewal_receipt_reject_update BEFORE UPDATE ON logical_workflow_materialization_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_materialization_renewal_receipt_validate BEFORE INSERT ON logical_workflow_materialization_renewal_receipts FOR EACH ROW EXECUTE FUNCTION automata_validate_materialization_real_claim_renewal_receipt();

CREATE TRIGGER logical_workflow_materialization_selection_delete BEFORE DELETE ON logical_workflow_materialization_work_selections FOR EACH ROW EXECUTE FUNCTION automata_enforce_materialization_selection_receipt_delete();

CREATE CONSTRAINT TRIGGER logical_workflow_materialization_selection_finalize AFTER INSERT OR UPDATE ON logical_workflow_materialization_work_selections DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_final_materialization_work_selection();

CREATE TRIGGER logical_workflow_materialization_selection_truncate BEFORE TRUNCATE ON logical_workflow_materialization_work_selections FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_materialization_selection_validate BEFORE INSERT OR UPDATE ON logical_workflow_materialization_work_selections FOR EACH ROW EXECUTE FUNCTION automata_validate_materialization_work_selection_transition();

CREATE CONSTRAINT TRIGGER logical_workflow_preparation_binding_closure AFTER INSERT ON logical_workflow_activation_preparations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_preparation_binding_state_closure();

CREATE CONSTRAINT TRIGGER logical_workflow_preparation_claim_closure AFTER INSERT OR UPDATE ON logical_workflow_activation_preparation_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_preparation_binding_state_closure();

CREATE CONSTRAINT TRIGGER logical_workflow_preparation_claim_lineage AFTER INSERT OR UPDATE ON logical_workflow_activation_preparation_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_preparation_claim_lineage();

CREATE TRIGGER logical_workflow_preparation_claims_00_runtime_policy BEFORE INSERT ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_preparation_claims_01_runner_policy BEFORE INSERT OR UPDATE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_require_preparation_runner_policy_provenance();

CREATE TRIGGER logical_workflow_preparation_claims_02_transition BEFORE INSERT OR UPDATE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_preparation_claim_transition();

CREATE TRIGGER logical_workflow_preparation_claims_policy_immutable BEFORE UPDATE ON logical_workflow_activation_preparation_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_preparation_claims_truncate BEFORE TRUNCATE ON logical_workflow_activation_preparation_claims FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_preparation_outputs_truncate BEFORE TRUNCATE ON logical_workflow_activation_preparation_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_preparation_prerequisites_truncate BEFORE TRUNCATE ON logical_workflow_activation_preparation_prerequisites FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_preparations_00_runtime_policy BEFORE INSERT ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_preparations_01_active_unquarantined BEFORE INSERT ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_require_active_unquarantined_phase_insert();

CREATE TRIGGER logical_workflow_preparations_policy_immutable BEFORE UPDATE ON logical_workflow_activation_preparations FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_preparations_truncate BEFORE TRUNCATE ON logical_workflow_activation_preparations FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_publication_count_exact AFTER INSERT ON logical_workflow_activation_publications DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_instance_count();

CREATE CONSTRAINT TRIGGER logical_workflow_publication_job_state_closure AFTER INSERT ON logical_workflow_activation_publications DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_activation_publication_state_closure();

CREATE TRIGGER logical_workflow_publications_00_runtime_policy BEFORE INSERT ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_runtime_policy_propagation();

CREATE TRIGGER logical_workflow_publications_01_active_unquarantined BEFORE INSERT ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_require_active_unquarantined_phase_insert();

CREATE TRIGGER logical_workflow_publications_policy_immutable BEFORE UPDATE ON logical_workflow_activation_publications FOR EACH ROW EXECUTE FUNCTION automata_enforce_runtime_policy_columns_immutable();

CREATE TRIGGER logical_workflow_result_selection_replay_horizons_enforce BEFORE UPDATE ON logical_workflow_result_selection_replay_horizons FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_result_replay_horizon();

CREATE TRIGGER logical_workflow_result_selection_replay_horizons_reject_delete BEFORE DELETE ON logical_workflow_result_selection_replay_horizons FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_result_selection_replay_horizons_reject_trunca BEFORE TRUNCATE ON logical_workflow_result_selection_replay_horizons FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_reusable_call_mappings_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_call_output_mappings FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_call_mappings_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_output_mappings FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_call_results_00_lock BEFORE INSERT ON logical_workflow_reusable_call_results FOR EACH ROW EXECUTE FUNCTION automata_lock_reusable_call_result();

CREATE TRIGGER logical_workflow_reusable_call_results_reject_delete BEFORE DELETE ON logical_workflow_reusable_call_results FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_call_results_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_results FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_call_results_seal BEFORE UPDATE ON logical_workflow_reusable_call_results FOR EACH ROW EXECUTE FUNCTION automata_seal_reusable_call_result();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_call_results_validate AFTER INSERT OR UPDATE ON logical_workflow_reusable_call_results DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_result();

CREATE TRIGGER logical_workflow_reusable_calls_00_lock BEFORE INSERT ON logical_workflow_reusable_call_publications FOR EACH ROW EXECUTE FUNCTION automata_lock_reusable_call_publication();

CREATE TRIGGER logical_workflow_reusable_calls_credentials_exact BEFORE UPDATE OF child_graph_sealed_at_ms ON logical_workflow_reusable_call_publications FOR EACH ROW EXECUTE FUNCTION automata_require_exact_reusable_child_credentials_at_seal();

CREATE TRIGGER logical_workflow_reusable_calls_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_publications FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_calls_reject_delete BEFORE DELETE ON logical_workflow_reusable_call_publications FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_calls_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_publications FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_calls_seal BEFORE UPDATE ON logical_workflow_reusable_call_publications FOR EACH ROW EXECUTE FUNCTION automata_seal_reusable_call_publication();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_calls_validate AFTER INSERT OR UPDATE ON logical_workflow_reusable_call_publications DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_publication();

CREATE TRIGGER logical_workflow_reusable_catalog_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_workflow_catalog FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_catalog_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_workflow_catalog FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_catalog_validate_expansion AFTER INSERT ON logical_workflow_reusable_workflow_catalog DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_contracts_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_output_contracts FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_dependencies_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_expanded_dependencies FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_dependencies_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_expanded_dependencies FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_dependencies_validate_expansion AFTER INSERT ON logical_workflow_reusable_expanded_dependencies DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_expansions_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_invocation_expansions FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_expansions_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_invocation_expansions FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_inputs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_input_bindings FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_inputs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_input_bindings FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_inputs_validate_expansion AFTER INSERT ON logical_workflow_reusable_input_bindings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_invocations_validate_expansion AFTER INSERT ON logical_workflow_reusable_invocation_expansions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_jobs_credential_requirements_validate BEFORE INSERT ON logical_workflow_reusable_expanded_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_job_credential_requirements();

CREATE TRIGGER logical_workflow_reusable_jobs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_expanded_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_jobs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_expanded_jobs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_jobs_validate_expansion AFTER INSERT ON logical_workflow_reusable_expanded_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_mappings_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_output_mappings FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_output_contracts_00_lock BEFORE INSERT ON logical_workflow_reusable_call_output_contracts FOR EACH ROW EXECUTE FUNCTION automata_lock_reusable_call_output_contract();

CREATE TRIGGER logical_workflow_reusable_output_contracts_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_call_output_contracts FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_output_contracts_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_output_contracts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_output_contracts_validate AFTER INSERT ON logical_workflow_reusable_call_output_contracts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_output_contract();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_output_mappings_validate AFTER INSERT ON logical_workflow_reusable_call_output_mappings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_output_contract();

CREATE TRIGGER logical_workflow_reusable_outputs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_outputs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_outputs_validate_expansion AFTER INSERT ON logical_workflow_reusable_outputs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_perm_snapshots_validate AFTER INSERT ON logical_workflow_reusable_permission_snapshots DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_permission_grants_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_permission_grants FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_permission_grants_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_permission_grants FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_permission_grants_validate_expansion AFTER INSERT ON logical_workflow_reusable_permission_grants DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_permission_snapshots_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_permission_snapshots FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_permission_snapshots_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_permission_snapshots FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_result_jobs_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_result_jobs FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_result_jobs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_call_result_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_result_jobs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_result_jobs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_result_jobs_validate AFTER INSERT ON logical_workflow_reusable_call_result_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_result();

CREATE TRIGGER logical_workflow_reusable_result_outputs_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_result_outputs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_call_result_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE TRIGGER logical_workflow_reusable_result_outputs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_call_result_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_runtime_evidence_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_result_outputs_validate AFTER INSERT ON logical_workflow_reusable_call_result_outputs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_call_result();

CREATE TRIGGER logical_workflow_reusable_results_freeze_for_run_result BEFORE INSERT OR DELETE ON logical_workflow_reusable_call_results FOR EACH ROW EXECUTE FUNCTION automata_freeze_logical_workflow_run_graph();

CREATE TRIGGER logical_workflow_reusable_runs_lock_expansion_window BEFORE INSERT ON logical_workflow_reusable_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_lock_reusable_workflow_expansion_window();

CREATE TRIGGER logical_workflow_reusable_runs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_runs_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_workflow_runs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_runs_validate_expansion AFTER INSERT ON logical_workflow_reusable_workflow_runs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_reusable_secrets_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_reusable_secret_bindings FOR EACH ROW EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE TRIGGER logical_workflow_reusable_secrets_reject_truncate BEFORE TRUNCATE ON logical_workflow_reusable_secret_bindings FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_reusable_workflow_ledger_mutation();

CREATE CONSTRAINT TRIGGER logical_workflow_reusable_secrets_validate_expansion AFTER INSERT ON logical_workflow_reusable_secret_bindings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_reusable_workflow_expansion();

CREATE TRIGGER logical_workflow_run_result_claims_enforce_transition BEFORE UPDATE ON logical_workflow_run_result_claims FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_run_result_claim_transition();

CREATE TRIGGER logical_workflow_run_result_claims_validate BEFORE INSERT OR UPDATE ON logical_workflow_run_result_claims FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_run_result_claim();

CREATE TRIGGER logical_workflow_run_result_jobs_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_run_result_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_run_result_mutation();

CREATE TRIGGER logical_workflow_run_result_jobs_validate BEFORE INSERT ON logical_workflow_run_result_jobs FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_run_result_job();

CREATE TRIGGER logical_workflow_run_results_reject_mutation BEFORE DELETE OR UPDATE ON logical_workflow_run_results FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_run_result_mutation();

CREATE TRIGGER logical_workflow_run_results_validate BEFORE INSERT ON logical_workflow_run_results FOR EACH ROW EXECUTE FUNCTION automata_validate_logical_workflow_run_result();

CREATE TRIGGER logical_workflow_runs_00_admission_graph_seal BEFORE INSERT OR UPDATE ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_admission_graph_seal();

CREATE TRIGGER logical_workflow_runs_00_require_runner_requirements_current BEFORE INSERT ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_require_logical_workflow_runner_requirements_current();

CREATE TRIGGER logical_workflow_runs_base_context_immutable BEFORE UPDATE OF base_context_digest, base_context_object_key, base_context_size_bytes, base_context_media_type, base_context_schema ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_run_base_context_mutation();

CREATE TRIGGER logical_workflow_runs_enforce_immutable BEFORE UPDATE ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_marker_immutable();

CREATE TRIGGER logical_workflow_runs_guard_run_result BEFORE UPDATE ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_guard_logical_workflow_marker_run_result();

CREATE TRIGGER logical_workflow_runs_reject_result_source_delete BEFORE DELETE ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_runs_reject_result_source_truncate BEFORE TRUNCATE ON logical_workflow_runs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_logical_workflow_result_evidence_removal();

CREATE TRIGGER logical_workflow_runs_require_classified_credentials BEFORE UPDATE OF admission_graph_sealed_at_ms ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_require_classified_credentials_before_graph_seal();

CREATE CONSTRAINT TRIGGER logical_workflow_runs_require_nonempty_root AFTER INSERT OR UPDATE ON logical_workflow_runs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_logical_workflow_nonempty_root();

CREATE CONSTRAINT TRIGGER logical_workflow_runs_require_runtime_policy_pin AFTER INSERT ON logical_workflow_runs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_workflow_runtime_policy_pin();

CREATE TRIGGER logical_workflow_runs_runner_requirements_schema_immutable BEFORE UPDATE OF runner_requirements_schema ON logical_workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_requirements_schema_immutable();

CREATE TRIGGER logical_workflow_runtime_policy_pins_00_provenance BEFORE INSERT ON logical_workflow_runtime_policy_pins FOR EACH ROW EXECUTE FUNCTION automata_require_workflow_runtime_policy_pin_provenance();

CREATE TRIGGER logical_workflow_runtime_policy_pins_reject_delete BEFORE DELETE ON logical_workflow_runtime_policy_pins FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER logical_workflow_runtime_policy_pins_reject_truncate BEFORE TRUNCATE ON logical_workflow_runtime_policy_pins FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER logical_workflow_runtime_policy_pins_reject_update BEFORE UPDATE ON logical_workflow_runtime_policy_pins FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER logical_workflow_selection_horizon_delete BEFORE DELETE ON logical_workflow_work_selection_replay_horizons FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_selection_horizon_truncate BEFORE TRUNCATE ON logical_workflow_work_selection_replay_horizons FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_work_evidence_mutation();

CREATE TRIGGER logical_workflow_selection_horizon_update BEFORE UPDATE ON logical_workflow_work_selection_replay_horizons FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_work_selection_horizon();

CREATE TRIGGER workflow_rerun_attempt_jobs_no_truncate BEFORE TRUNCATE ON workflow_rerun_attempt_jobs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_attempt_job_mutation();

CREATE TRIGGER workflow_rerun_attempt_jobs_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_attempt_jobs FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_attempt_job_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempt_jobs_validate_classification AFTER INSERT ON workflow_rerun_attempt_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_job_classification();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempt_jobs_validate_graph AFTER INSERT ON workflow_rerun_attempt_jobs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_graph_exact();

CREATE TRIGGER workflow_rerun_attempts_no_truncate BEFORE TRUNCATE ON workflow_rerun_attempts FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_attempt_mutation();

CREATE TRIGGER workflow_rerun_attempts_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_attempts FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_attempt_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempts_require_audit_evidence AFTER INSERT ON workflow_rerun_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_workflow_rerun_audit_evidence();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempts_validate_concurrency_slot AFTER INSERT ON workflow_rerun_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_concurrency_slot();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempts_validate_graph AFTER INSERT ON workflow_rerun_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_graph_exact();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempts_validate_lineage AFTER INSERT ON workflow_rerun_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_attempt_lineage();

CREATE CONSTRAINT TRIGGER workflow_rerun_attempts_validate_public_identity AFTER INSERT ON workflow_rerun_attempts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_run_public_rerun_identity();

CREATE TRIGGER workflow_rerun_audit_evidence_insert_guard BEFORE INSERT ON workflow_rerun_audit_evidence FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_audit_evidence();

CREATE TRIGGER workflow_rerun_audit_evidence_no_truncate BEFORE TRUNCATE ON workflow_rerun_audit_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_audit_evidence_mutation();

CREATE TRIGGER workflow_rerun_audit_evidence_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_audit_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_audit_evidence_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_audit_evidence_require_exact AFTER INSERT ON workflow_rerun_audit_evidence DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_workflow_rerun_audit_evidence();

CREATE TRIGGER workflow_rerun_carried_job_outputs_no_truncate BEFORE TRUNCATE ON workflow_rerun_carried_job_outputs FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_carry_mutation();

CREATE TRIGGER workflow_rerun_carried_job_outputs_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_carried_job_outputs FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_carry_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_carried_job_outputs_validate_source AFTER INSERT ON workflow_rerun_carried_job_outputs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_carried_result_source();

CREATE TRIGGER workflow_rerun_carried_job_results_no_truncate BEFORE TRUNCATE ON workflow_rerun_carried_job_results FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_carry_mutation();

CREATE TRIGGER workflow_rerun_carried_job_results_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_carried_job_results FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_carry_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_carried_job_results_validate_source AFTER INSERT ON workflow_rerun_carried_job_results DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_carried_result_source();

CREATE CONSTRAINT TRIGGER workflow_rerun_carried_results_validate_classification AFTER INSERT ON workflow_rerun_carried_job_results DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_job_classification();

CREATE TRIGGER workflow_rerun_check_evidence_insert_guard BEFORE INSERT ON workflow_rerun_check_evidence FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_check_evidence();

CREATE TRIGGER workflow_rerun_check_evidence_no_truncate BEFORE TRUNCATE ON workflow_rerun_check_evidence FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_check_evidence_mutation();

CREATE TRIGGER workflow_rerun_check_evidence_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_check_evidence FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_check_evidence_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_executed_results_validate_classification AFTER INSERT ON logical_workflow_job_results DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_job_classification();

CREATE TRIGGER workflow_rerun_requests_no_truncate BEFORE TRUNCATE ON workflow_rerun_requests FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_rerun_request_mutation();

CREATE TRIGGER workflow_rerun_requests_no_update_delete BEFORE DELETE OR UPDATE ON workflow_rerun_requests FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_rerun_request_mutation();

CREATE CONSTRAINT TRIGGER workflow_rerun_requests_validate_completion AFTER INSERT ON workflow_rerun_requests DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_request_complete();

CREATE CONSTRAINT TRIGGER workflow_rerun_requests_validate_graph AFTER INSERT ON workflow_rerun_requests DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_rerun_graph_exact();

CREATE TRIGGER workflow_runs_00_require_runner_requirements_current BEFORE INSERT ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_require_workflow_run_runner_requirements_current();

CREATE TRIGGER workflow_runs_default_public_run_id_alias BEFORE INSERT ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_default_workflow_public_run_id_alias();

CREATE TRIGGER workflow_runs_enforce_concurrency_policy_immutable BEFORE UPDATE ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_concurrency_policy_immutable();

CREATE TRIGGER workflow_runs_enforce_plan_immutable BEFORE UPDATE ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_logical_workflow_run_immutable();

CREATE TRIGGER workflow_runs_fence_plan_completion BEFORE UPDATE ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_fence_logical_workflow_run_completion();

CREATE TRIGGER workflow_runs_guard_plan_result BEFORE UPDATE ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_guard_workflow_run_plan_result();

CREATE TRIGGER workflow_runs_id_alias_immutable BEFORE UPDATE OF run_id_alias ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_run_id_alias_mutation();

CREATE TRIGGER workflow_runs_publication_snapshot_immutable BEFORE UPDATE ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_workflow_run_publication_snapshot_immutable();

CREATE TRIGGER workflow_runs_rerun_identity_immutable BEFORE UPDATE OF public_run_id_alias, triggering_actor, concurrency_cancel_in_progress ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_run_rerun_identity_mutation();

CREATE TRIGGER workflow_runs_runner_requirements_schema_immutable BEFORE UPDATE OF runner_requirements_schema ON workflow_runs FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_run_requirements_schema_immutable();

CREATE CONSTRAINT TRIGGER workflow_runs_validate_public_rerun_identity AFTER INSERT ON workflow_runs DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_validate_workflow_run_public_rerun_identity();

CREATE TRIGGER workflow_runtime_policy_current_enforce BEFORE INSERT OR UPDATE ON workflow_runtime_policy_current FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_runtime_policy_current();

CREATE TRIGGER workflow_runtime_policy_current_reject_delete BEFORE DELETE ON workflow_runtime_policy_current FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_runtime_policy_current_reject_truncate BEFORE TRUNCATE ON workflow_runtime_policy_current FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE CONSTRAINT TRIGGER workflow_runtime_policy_current_requires_manifest AFTER INSERT OR UPDATE ON workflow_runtime_policy_current DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_current_manifest_runtime_policy_pair();

CREATE TRIGGER workflow_runtime_policy_features_enforce BEFORE INSERT OR UPDATE ON workflow_runtime_policy_features FOR EACH ROW EXECUTE FUNCTION automata_require_staging_workflow_runtime_policy();

CREATE TRIGGER workflow_runtime_policy_features_reject_delete BEFORE DELETE ON workflow_runtime_policy_features FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_runtime_policy_features_reject_truncate BEFORE TRUNCATE ON workflow_runtime_policy_features FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_runtime_policy_mappings_enforce BEFORE INSERT OR UPDATE ON workflow_runtime_policy_mappings FOR EACH ROW EXECUTE FUNCTION automata_require_staging_workflow_runtime_policy();

CREATE TRIGGER workflow_runtime_policy_mappings_reject_delete BEFORE DELETE ON workflow_runtime_policy_mappings FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_runtime_policy_mappings_reject_truncate BEFORE TRUNCATE ON workflow_runtime_policy_mappings FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE CONSTRAINT TRIGGER workflow_runtime_policy_revision_must_seal AFTER INSERT OR UPDATE ON workflow_runtime_policy_revisions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION automata_require_sealed_workflow_runtime_policy_revision();

CREATE TRIGGER workflow_runtime_policy_revisions_enforce BEFORE INSERT OR UPDATE ON workflow_runtime_policy_revisions FOR EACH ROW EXECUTE FUNCTION automata_enforce_workflow_runtime_policy_revision();

CREATE TRIGGER workflow_runtime_policy_revisions_reject_delete BEFORE DELETE ON workflow_runtime_policy_revisions FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_runtime_policy_revisions_reject_truncate BEFORE TRUNCATE ON workflow_runtime_policy_revisions FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_runtime_policy_retained_mutation();

CREATE TRIGGER workflow_variable_versions_append_only BEFORE DELETE OR UPDATE ON workflow_variable_versions FOR EACH ROW EXECUTE FUNCTION automata_reject_workflow_variable_version_mutation();

CREATE TRIGGER workflow_variable_versions_no_truncate BEFORE TRUNCATE ON workflow_variable_versions FOR EACH STATEMENT EXECUTE FUNCTION automata_reject_workflow_variable_version_mutation();

CREATE TRIGGER workflow_variables_guard BEFORE UPDATE ON workflow_variables FOR EACH ROW EXECUTE FUNCTION automata_workflow_variable_guard();
