#![forbid(unsafe_code)]
#![deny(missing_docs)]
//! Canonical protobuf framing for the Automata runner protocol.
//!
//! Domain messages remain owned by [`automata_ci_protocol`]. This crate is a
//! deliberately narrow adapter: its generated DTOs are private, every decode
//! is size-checked before protobuf allocation, and callers only receive the
//! validated transport-neutral messages.
//!
//! `proto/automata/runner/v1/runner.proto` is authoritative. Its prost DTOs
//! are checked in, so production and cross-compilation never require `protoc`,
//! a build script, or a native code generator.
//!
//! Decoding deliberately accepts unknown protobuf fields for rolling upgrades.
//! Consequently, application idempotency digests must be computed from the
//! validated message's canonical re-encoding, never from the untrusted input
//! frame: protobuf permits multiple byte representations of the same message.

mod decode;
mod encode;
mod error;
// This is mechanically generated by prost-build from the checked-in schema.
// Its shapes are private and intentionally retain prost's conventional API.
#[allow(clippy::all, clippy::pedantic)]
mod wire {
    include!("generated/automata.runner.v1.rs");
}

pub use decode::{
    decode_job_ir, decode_job_runtime_context, decode_runner_frame, decode_runtime_authorities,
    decode_server_frame,
};
pub use encode::{
    encode_job_ir, encode_job_runtime_context, encode_runner_frame, encode_runtime_authorities,
    encode_server_frame,
};
pub use error::{DecodeError, EncodeError};

/// Stable protobuf package implemented by this adapter.
pub const PROTOBUF_PACKAGE: &str = "automata.runner.v1";
