[package]
name = "automata-ci-secret-postgres"
description = "Encrypted PostgreSQL built-in secret provider for Automata"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
async-trait.workspace = true
automata-ci-key-management.workspace = true
automata-ci-secret.workspace = true
automata-ci-store.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
automata-ci-auth.workspace = true
tokio.workspace = true

[lints]
workspace = true
