[package]
name = "automata-ci-local"
description = "Cross-platform local installation support for Automata"
publish.workspace = true
readme = "README.md"
keywords = ["ci", "github-actions", "local-development", "containers"]
categories = ["development-tools"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
async-trait.workspace = true
automata-ci-core.workspace = true
automata-ci-workflow-github.workspace = true
bytes.workspace = true
cap-fs-ext.workspace = true
cap-std.workspace = true
flate2.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
rustix.workspace = true

[target.'cfg(windows)'.dependencies]
processkit.workspace = true

[lints]
workspace = true
