// @generated by scripts/ui/regenerate-renderer.sh; do not edit by hand.

pub(crate) const COMPONENT_BYTES: &[u8] = include_bytes!(
    "../../../ui/renderer/assets/renderer-e805802054512ca7e7de32ae2305570c2d7cab655438bff2ffaea103e9d24f7d.wasm"
);
pub(crate) const COMPONENT_SHA256: &str =
    "e805802054512ca7e7de32ae2305570c2d7cab655438bff2ffaea103e9d24f7d";

pub(crate) const CLIENT_SCRIPT_BYTES: &[u8] = include_bytes!(
    "../../../ui/renderer/assets/client-7a846e6cad51a817f842b7f6c435ba606398d9aa45af3cf055c7f1407d0807ab.js"
);
pub(crate) const CLIENT_SCRIPT_SHA256: &str =
    "7a846e6cad51a817f842b7f6c435ba606398d9aa45af3cf055c7f1407d0807ab";
pub(crate) const CLIENT_SCRIPT_PATH: &str = "/assets/entry-client-CXNIQG-W.js";

pub(crate) const CLIENT_STYLE_BYTES: &[u8] = include_bytes!(
    "../../../ui/renderer/assets/styles-4d2ecd9ab62605346602e0856d366c14599e0e1d265d19bc05f11ac1f61ae58b.css"
);
pub(crate) const CLIENT_STYLE_SHA256: &str =
    "4d2ecd9ab62605346602e0856d366c14599e0e1d265d19bc05f11ac1f61ae58b";
pub(crate) const CLIENT_STYLE_PATH: &str = "/assets/entry-client-DnE6LV8l.css";
