[package]
name = "automata-ci-provider-postgres"
description = "PostgreSQL provider manifest repository for Automata"
publish.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
automata-ci-blob.workspace = true
automata-ci-core.workspace = true
automata-ci-key-management.workspace = true
automata-ci-provider.workspace = true
sha2.workspace = true
sqlx.workspace = true
uuid.workspace = true

[dev-dependencies]
automata-ci-postgres = { workspace = true, features = ["test-support"] }
automata-ci-store.workspace = true
automata-ci-store-postgres.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
