// @generated by scripts/ui/regenerate-renderer.sh; do not edit by hand.

pub(crate) const COMPONENT_BYTES: &[u8] = include_bytes!(
    "../assets/renderer-5b19ac6fe7c9d7fcc50ac84606ab97209c38a394fc17aa8692274d628eabb890.wasm"
);
pub(crate) const COMPONENT_SHA256: &str =
    "5b19ac6fe7c9d7fcc50ac84606ab97209c38a394fc17aa8692274d628eabb890";

pub(crate) const CLIENT_SCRIPT_BYTES: &[u8] = include_bytes!(
    "../assets/client-191e2c5ea2a7c03fe9a67e2eab4e138a12a9c527d107afd588a562d59df055b5.js"
);
pub(crate) const CLIENT_SCRIPT_SHA256: &str =
    "191e2c5ea2a7c03fe9a67e2eab4e138a12a9c527d107afd588a562d59df055b5";
pub(crate) const CLIENT_SCRIPT_PATH: &str = "/assets/entry-client-BRzAGVbD.js";

pub(crate) const CLIENT_STYLE_BYTES: &[u8] = include_bytes!(
    "../assets/styles-607d44447964098c0df6f74676c74050e5e4e13385620640814ef35111ac245b.css"
);
pub(crate) const CLIENT_STYLE_SHA256: &str =
    "607d44447964098c0df6f74676c74050e5e4e13385620640814ef35111ac245b";
pub(crate) const CLIENT_STYLE_PATH: &str = "/assets/entry-client-BWZFEySi.css";
