// @generated by scripts/ui/sync-render-contract.mjs; do not edit by hand.

/// Maximum UTF-8 wire size accepted for one serialized render request.
pub const MAX_RENDER_REQUEST_UTF8_BYTES: usize = 2_097_152;

/// Maximum UTF-8 size returned for one rendered HTML document.
pub const MAX_RENDERED_HTML_UTF8_BYTES: usize = 8_388_608;
