// @generated by scripts/ui/regenerate-renderer.sh; do not edit by hand.

pub(crate) const COMPONENT_BYTES: &[u8] = include_bytes!(
    "../assets/renderer-359d1401320a15f7a7b319063278ce7c28ba9a76876b97f5b7e53ef15fd40121.wasm"
);
pub(crate) const COMPONENT_SHA256: &str =
    "359d1401320a15f7a7b319063278ce7c28ba9a76876b97f5b7e53ef15fd40121";

pub(crate) const CLIENT_SCRIPT_BYTES: &[u8] = include_bytes!(
    "../assets/client-fbc272514cd16c07e9d0f08432894529d6b8216aa760796e8d6f42ecdbb30fcf.js"
);
pub(crate) const CLIENT_SCRIPT_SHA256: &str =
    "fbc272514cd16c07e9d0f08432894529d6b8216aa760796e8d6f42ecdbb30fcf";
pub(crate) const CLIENT_SCRIPT_PATH: &str = "/assets/entry-client-zG3m30zN.js";

pub(crate) const CLIENT_STYLE_BYTES: &[u8] = include_bytes!(
    "../assets/styles-9c647c3d86e80fc1170174c99925cd5dc29cf3f643221c89324a8b993863ece6.css"
);
pub(crate) const CLIENT_STYLE_SHA256: &str =
    "9c647c3d86e80fc1170174c99925cd5dc29cf3f643221c89324a8b993863ece6";
pub(crate) const CLIENT_STYLE_PATH: &str = "/assets/entry-client-jQ4oIGWe.css";
