// @generated by scripts/ui/regenerate-renderer.sh; do not edit by hand.

pub(crate) const COMPONENT_BYTES: &[u8] = include_bytes!(
    "../assets/renderer-84103aaa2bee1eada0d544c7660ef8c96e1624958a5c2ebb31962345d3de42e2.wasm"
);
pub(crate) const COMPONENT_SHA256: &str =
    "84103aaa2bee1eada0d544c7660ef8c96e1624958a5c2ebb31962345d3de42e2";

pub(crate) const CLIENT_SCRIPT_BYTES: &[u8] = include_bytes!(
    "../assets/client-1ad90c63cc3d36f342a44ed586a2487b09c4e7b869d2240e8c9875de15e74114.js"
);
pub(crate) const CLIENT_SCRIPT_SHA256: &str =
    "1ad90c63cc3d36f342a44ed586a2487b09c4e7b869d2240e8c9875de15e74114";
pub(crate) const CLIENT_SCRIPT_PATH: &str = "/assets/entry-client-DcMI937d.js";

pub(crate) const CLIENT_STYLE_BYTES: &[u8] = include_bytes!(
    "../assets/styles-9c647c3d86e80fc1170174c99925cd5dc29cf3f643221c89324a8b993863ece6.css"
);
pub(crate) const CLIENT_STYLE_SHA256: &str =
    "9c647c3d86e80fc1170174c99925cd5dc29cf3f643221c89324a8b993863ece6";
pub(crate) const CLIENT_STYLE_PATH: &str = "/assets/entry-client-jQ4oIGWe.css";
