[package]
name = "automata-action-github"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Bounded GitHub Actions metadata decoder for Automata"
publish = false

[dependencies]
automata-action.workspace = true
saphyr-parser.workspace = true
thiserror.workspace = true

[dev-dependencies]
automata-blob-s3.workspace = true
automata-github.workspace = true
automata-scm.workspace = true
bytes.workspace = true
flate2.workspace = true
static_assertions.workspace = true
tar.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
