#![forbid(unsafe_code)]

use std::env;
use std::ffi::OsStr;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use sha2::{Digest, Sha256};

const MANIFEST_NAME: &str = "manifest.json";
const MAX_COMPONENT_BYTES: u64 = 16 * 1024 * 1024;
const MAX_CLIENT_ASSET_BYTES: u64 = 4 * 1024 * 1024;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct RendererManifest {
    schema_version: u32,
    component: String,
    script: ClientAsset,
    stylesheet: ClientAsset,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct ClientAsset {
    file: String,
    public_path: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct RenderContract {
    schema_version: u32,
    max_request_utf8_bytes: usize,
    max_rendered_html_utf8_bytes: usize,
}

struct VerifiedAsset {
    path: PathBuf,
    digest: String,
}

fn main() {
    if let Err(error) = run() {
        panic!("Automata UI renderer build failed: {error}");
    }
}

fn run() -> Result<(), String> {
    println!("cargo:rerun-if-env-changed=AUTOMATA_UI_RENDERER_BUILD_DIR");

    let crate_directory = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "Cargo did not provide CARGO_MANIFEST_DIR".to_owned())?,
    );
    let output_directory = PathBuf::from(
        env::var_os("OUT_DIR").ok_or_else(|| "Cargo did not provide OUT_DIR".to_owned())?,
    );
    let build_directory = renderer_build_directory(&crate_directory)?;
    let manifest_path = build_directory.join(MANIFEST_NAME);
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest: RendererManifest = read_json(&manifest_path, "renderer manifest")?;
    if manifest.schema_version != 1 {
        return Err(format!(
            "unsupported renderer manifest schema {}; expected 1",
            manifest.schema_version
        ));
    }

    let assets_directory =
        canonical_directory(&build_directory.join("assets"), "renderer asset directory")?;
    if assets_directory.parent() != Some(build_directory.as_path()) {
        return Err("renderer asset directory escapes its build directory".to_owned());
    }
    let component = verify_asset(
        &assets_directory,
        &manifest.component,
        "renderer-",
        ".wasm",
        MAX_COMPONENT_BYTES,
    )?;
    let script = verify_asset(
        &assets_directory,
        &manifest.script.file,
        "client-",
        ".js",
        MAX_CLIENT_ASSET_BYTES,
    )?;
    let stylesheet = verify_asset(
        &assets_directory,
        &manifest.stylesheet.file,
        "styles-",
        ".css",
        MAX_CLIENT_ASSET_BYTES,
    )?;
    verify_public_path(&manifest.script.public_path, "entry-client-", ".js")?;
    verify_public_path(&manifest.stylesheet.public_path, "entry-client-", ".css")?;
    verify_exact_asset_set(
        &assets_directory,
        [&component.path, &script.path, &stylesheet.path],
    )?;

    let generated_assets = format!(
        "// @generated by build.rs; do not edit by hand.\n\
         pub(crate) const COMPONENT_BYTES: &[u8] = include_bytes!({component_path});\n\
         pub(crate) const COMPONENT_SHA256: &str = {component_digest};\n\
         pub(crate) const CLIENT_SCRIPT_BYTES: &[u8] = include_bytes!({script_path});\n\
         pub(crate) const CLIENT_SCRIPT_SHA256: &str = {script_digest};\n\
         pub(crate) const CLIENT_SCRIPT_PATH: &str = {script_public_path};\n\
         pub(crate) const CLIENT_STYLE_BYTES: &[u8] = include_bytes!({style_path});\n\
         pub(crate) const CLIENT_STYLE_SHA256: &str = {style_digest};\n\
         pub(crate) const CLIENT_STYLE_PATH: &str = {style_public_path};\n",
        component_path = rust_path_literal(&component.path)?,
        component_digest = rust_string_literal(&component.digest)?,
        script_path = rust_path_literal(&script.path)?,
        script_digest = rust_string_literal(&script.digest)?,
        script_public_path = rust_string_literal(&manifest.script.public_path)?,
        style_path = rust_path_literal(&stylesheet.path)?,
        style_digest = rust_string_literal(&stylesheet.digest)?,
        style_public_path = rust_string_literal(&manifest.stylesheet.public_path)?,
    );
    write_generated(
        &output_directory.join("generated_assets.rs"),
        &generated_assets,
    )?;

    let contract_path = crate_directory.join("contract.json");
    println!("cargo:rerun-if-changed={}", contract_path.display());
    let contract: RenderContract = read_json(&contract_path, "render contract")?;
    if contract.schema_version != 1
        || contract.max_request_utf8_bytes == 0
        || contract.max_rendered_html_utf8_bytes == 0
    {
        return Err("render contract must use schema 1 and positive byte limits".to_owned());
    }
    let generated_contract = format!(
        "// @generated by build.rs; do not edit by hand.\n\
         /// Maximum serialized UTF-8 render-request size accepted by the shared contract.\n\
         pub const MAX_RENDER_REQUEST_UTF8_BYTES: usize = {};\n\
         /// Maximum UTF-8 HTML response size accepted by the shared contract.\n\
         pub const MAX_RENDERED_HTML_UTF8_BYTES: usize = {};\n",
        rust_usize_literal(contract.max_request_utf8_bytes),
        rust_usize_literal(contract.max_rendered_html_utf8_bytes),
    );
    write_generated(
        &output_directory.join("generated_contract.rs"),
        &generated_contract,
    )?;
    Ok(())
}

fn renderer_build_directory(crate_directory: &Path) -> Result<PathBuf, String> {
    if let Some(configured) = env::var_os("AUTOMATA_UI_RENDERER_BUILD_DIR") {
        let configured = PathBuf::from(configured);
        if !configured.is_absolute() {
            return Err("AUTOMATA_UI_RENDERER_BUILD_DIR must be absolute".to_owned());
        }
        return canonical_directory(&configured, "configured renderer build directory");
    }

    let workspace_build = crate_directory.join("../../target/ui-renderer");
    if workspace_build.join(MANIFEST_NAME).is_file() {
        return canonical_directory(&workspace_build, "workspace renderer build directory");
    }

    let packaged_build = crate_directory.join("generated");
    if packaged_build.join(MANIFEST_NAME).is_file() {
        return canonical_directory(&packaged_build, "packaged renderer build directory");
    }

    Err(format!(
        "renderer build output is missing; run {} before Cargo, or set AUTOMATA_UI_RENDERER_BUILD_DIR",
        crate_directory
            .join("../../scripts/ui/reproduce-renderer-in-profile.sh")
            .display()
    ))
}

fn canonical_directory(path: &Path, label: &str) -> Result<PathBuf, String> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect {label} {}: {error}", path.display()))?;
    if !metadata.file_type().is_dir() || metadata.file_type().is_symlink() {
        return Err(format!(
            "{label} must be a real directory: {}",
            path.display()
        ));
    }
    fs::canonicalize(path)
        .map_err(|error| format!("cannot resolve {label} {}: {error}", path.display()))
}

fn read_json<T: for<'de> Deserialize<'de>>(path: &Path, label: &str) -> Result<T, String> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| format!("cannot inspect {label} {}: {error}", path.display()))?;
    if !metadata.file_type().is_file() || metadata.file_type().is_symlink() {
        return Err(format!("{label} must be a real file: {}", path.display()));
    }
    if metadata.len() > 64 * 1024 {
        return Err(format!("{label} exceeds 64 KiB: {}", path.display()));
    }
    let bytes = fs::read(path)
        .map_err(|error| format!("cannot read {label} {}: {error}", path.display()))?;
    serde_json::from_slice(&bytes)
        .map_err(|error| format!("invalid {label} {}: {error}", path.display()))
}

fn verify_asset(
    directory: &Path,
    filename: &str,
    prefix: &str,
    suffix: &str,
    maximum_bytes: u64,
) -> Result<VerifiedAsset, String> {
    let digest = filename
        .strip_prefix(prefix)
        .and_then(|value| value.strip_suffix(suffix))
        .filter(|value| {
            value.len() == 64
                && value
                    .bytes()
                    .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
        })
        .ok_or_else(|| format!("invalid content-addressed renderer asset name: {filename}"))?;
    if Path::new(filename).file_name() != Some(OsStr::new(filename)) {
        return Err(format!("renderer asset name contains a path: {filename}"));
    }
    let path = directory.join(filename);
    let metadata = fs::symlink_metadata(&path)
        .map_err(|error| format!("cannot inspect renderer asset {}: {error}", path.display()))?;
    if !metadata.file_type().is_file() || metadata.file_type().is_symlink() {
        return Err(format!(
            "renderer asset must be a real file: {}",
            path.display()
        ));
    }
    if metadata.len() == 0 || metadata.len() > maximum_bytes {
        return Err(format!(
            "renderer asset size is outside 1..={maximum_bytes} bytes: {}",
            path.display()
        ));
    }
    let bytes = fs::read(&path)
        .map_err(|error| format!("cannot read renderer asset {}: {error}", path.display()))?;
    let actual = hex_digest(&bytes);
    if actual != digest {
        return Err(format!(
            "renderer asset digest does not match its filename: {}",
            path.display()
        ));
    }
    let path = fs::canonicalize(&path)
        .map_err(|error| format!("cannot resolve renderer asset {}: {error}", path.display()))?;
    Ok(VerifiedAsset {
        path,
        digest: digest.to_owned(),
    })
}

fn hex_digest(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut encoded = String::with_capacity(digest.len() * 2);
    for byte in digest {
        write!(&mut encoded, "{byte:02x}").expect("writing to a String cannot fail");
    }
    encoded
}

fn rust_path_literal(path: &Path) -> Result<String, String> {
    let path = path
        .to_str()
        .ok_or_else(|| format!("renderer asset path is not UTF-8: {}", path.display()))?;
    rust_string_literal(path)
}

fn rust_string_literal(value: &str) -> Result<String, String> {
    serde_json::to_string(value)
        .map_err(|error| format!("cannot encode generated Rust string literal: {error}"))
}

fn rust_usize_literal(value: usize) -> String {
    let digits = value.to_string();
    let mut literal = String::with_capacity(digits.len() + digits.len() / 3);
    for (index, digit) in digits.chars().enumerate() {
        if index > 0 && (digits.len() - index).is_multiple_of(3) {
            literal.push('_');
        }
        literal.push(digit);
    }
    literal
}

fn verify_public_path(path: &str, prefix: &str, suffix: &str) -> Result<(), String> {
    let Some(name) = path.strip_prefix("/assets/") else {
        return Err(format!(
            "client asset public path is not under /assets/: {path}"
        ));
    };
    let Some(hash) = name
        .strip_prefix(prefix)
        .and_then(|value| value.strip_suffix(suffix))
    else {
        return Err(format!(
            "client asset has an unexpected public path: {path}"
        ));
    };
    if hash.is_empty()
        || hash.len() > 64
        || !hash
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
    {
        return Err(format!(
            "client asset public path has an invalid hash: {path}"
        ));
    }
    Ok(())
}

fn verify_exact_asset_set<'a>(
    directory: &Path,
    expected: impl IntoIterator<Item = &'a PathBuf>,
) -> Result<(), String> {
    let mut expected = expected
        .into_iter()
        .map(|path| path.file_name().map(OsStr::to_owned))
        .collect::<Option<Vec<_>>>()
        .ok_or_else(|| "verified renderer asset has no filename".to_owned())?;
    expected.sort();
    let mut actual = Vec::new();
    for entry in fs::read_dir(directory).map_err(|error| {
        format!(
            "cannot list renderer assets {}: {error}",
            directory.display()
        )
    })? {
        let entry = entry.map_err(|error| format!("cannot list renderer asset: {error}"))?;
        actual.push(entry.file_name());
    }
    actual.sort();
    if actual != expected {
        return Err("renderer asset directory does not exactly match manifest.json".to_owned());
    }
    Ok(())
}

fn write_generated(path: &Path, contents: &str) -> Result<(), String> {
    let mut normalized = String::with_capacity(contents.len() + 1);
    write!(&mut normalized, "{}", contents.trim_end())
        .map_err(|error| format!("cannot format {}: {error}", path.display()))?;
    normalized.push('\n');
    fs::write(path, normalized).map_err(|error| format!("cannot write {}: {error}", path.display()))
}
